{
  "hash": "817a52485b75ae9d504724b3b3a9db22",
  "result": {
    "engine": "knitr",
    "markdown": "---\nlang: es\n---\n\n\n\n\n# Pronóstico de decesos diarios\n\n::: {.content-visible when-format=\"html\"}\n::: {style=\"text-align: justify\"}\nDe manera similar a la evaluación llevada a cabo en la base de datos de los casos confirmados de COVID-19 en Irán, se ejecutó un análisis para los datos de muertes por COVID-19 en Irán, abarcando el mismo período temporal, desde el 20 de febrero hasta el 15 de agosto de 2020. El propósito fue determinar si, de forma análoga, la red neuronal MLP demuestra un mejor ajuste a los datos en comparación con la técnica de series temporales Holt-Winters, o si, en este caso particular, la técnica Holt-Winters ofrece una mayor precisión.\n\nEs relevante señalar la presencia de datos faltantes para las fechas 21 de febrero, 1 de marzo y 5 de mayo de 2020 en el conjunto de datos. Por consiguiente, al igual que en los casos confirmados, se procedió con una interpolación promedio para sustituir dichos datos faltantes. La @fig-muertes exhibe la serie temporal resultante luego de estas correcciones.\n:::\n:::\n\n::: {.content-visible when-format=\"pdf\"}\n::: {style=\"text-align: justify\"}\nDe manera similar a la evaluación llevada a cabo en la base de datos de los casos confirmados de COVID-19 en Irán, se ejecutó un análisis para los datos de muertes por COVID-19 en Irán, abarcando el mismo período temporal, desde el 20 de febrero hasta el 15 de agosto de 2020. El propósito fue determinar si, de forma análoga, la red neuronal MLP demuestra un mejor ajuste a los datos en comparación con la técnica de series temporales Holt-Winters, o si, en este caso particular, la técnica Holt-Winters ofrece una mayor precisión.\n\nEs relevante señalar la presencia de datos faltantes para las fechas 21 de febrero, 1 de marzo y 5 de mayo de 2020 en el conjunto de datos. Por consiguiente, al igual que en los casos confirmados, se procedió con una interpolación promedio para sustituir dichos datos faltantes. La @fig-muertespdf exhibe la serie temporal resultante luego de estas correcciones.\n:::\n:::\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\n::: {.content-visible when-format=\"html\"}\n::: {#fig-muertes}\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](muertes_files/figure-epub/unnamed-chunk-3-1.png)\n:::\n:::\n\n\n\n\nSerie de tiempo de los casos de muerte por COVID-19 en Irán del 20-02-2020 al 15-08-2020\n:::\n:::\n\n::: {.content-visible when-format=\"pdf\"}\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Serie de tiempo de los casos de muerte por COVID-19 en Irán del 20-02-2020 al 15-08-2020](muertes_files/figure-epub/fig-muertespdf-1.png){#fig-muertespdf}\n:::\n:::\n\n\n\n:::\n\n## Pronóstico, comparación y métricas de rendimiento\n\n::: {style=\"text-align: justify\"}\nLa evaluación del desempeño de los métodos se realiza a través de la separación del conjunto de datos en entrenamiento y prueba. El set inicial, compuesto por el $70\\%$ de los datos, se emplea para el entrenamiento de los modelos, mientras que el $30\\%$ restante se reservará para llevar a cabo las pruebas pertinentes.\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nDeaths_ts <- ts(Deaths_ts,frequency=1) \ntsize <- round(0.7 * nrow(Deaths_df)) \ntrain_deaths <- window(Deaths_ts,end=tsize) \ntest_deaths <- window(Deaths_ts,start=tsize+1)\n```\n:::\n\n\n\n\n::: {style=\"text-align: justify\"}\nCon el propósito de llevar a cabo un análisis cuantitativo exhaustivo, se presenta a continuación una tabla comparativa de los resultados derivados de las dos técnicas implementadas (después de realizar el entrenamiento, modelado y pronóstico), y la base de datos de prueba. Posteriormente, se exhiben gráficas representativas de estos resultados. En la @fig-phwd se muestra el pronóstico mediante Holt-Winters acompañado de su respectivo intervalo de confianza. En contraste, en la @fig-pmlpd, la gráfica punteada en color rojo representa el comportamiento real de los datos, mientras que en azul se representa el pronóstico obtenido a través de la red MLP.\n:::\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n::: {.content-visible when-format=\"pdf\"}\n\n\n\n::: {#tbl-forecastdpdf .cell tbl-cap='Comparación de Resultados entre las técnicas y los datos reales para evaluar precisión'}\n::: {.cell-output .cell-output-stdout}\n\n```\n           Date Deaths Forecast_HW Forecast_MLP\nt+1  2020-06-24    121    125.8962     118.8623\nt+2  2020-06-25    133    122.3430     119.1069\nt+3  2020-06-26    134    130.6941     119.2441\nt+4  2020-06-27    109    126.9184     119.3710\nt+5  2020-06-28    125    135.4921     119.4854\nt+6  2020-06-29    144    131.4938     119.5887\nt+7  2020-06-30    162    140.2900     119.6819\nt+8  2020-07-01    147    136.0691     119.7660\nt+9  2020-07-02    141    145.0880     119.8417\nt+10 2020-07-03    148    140.6445     119.9100\nt+11 2020-07-04    154    149.8859     119.9715\nt+12 2020-07-05    148    145.2198     120.0269\nt+13 2020-07-06    163    154.6839     120.0768\nt+14 2020-07-07    160    149.7952     120.1218\nt+15 2020-07-08    200    159.4818     120.1623\nt+16 2020-07-09    153    154.3705     120.1988\nt+17 2020-07-10    221    164.2798     120.2318\nt+18 2020-07-11    142    158.9459     120.2615\nt+19 2020-07-12    188    169.0777     120.2883\nt+20 2020-07-13    194    163.5212     120.3126\nt+21 2020-07-14    203    173.8757     120.3345\nt+22 2020-07-15    179    168.0966     120.3544\nt+23 2020-07-16    199    178.6736     120.3724\nt+24 2020-07-17    198    172.6719     120.3887\nt+25 2020-07-18    183    183.4716     120.4035\nt+26 2020-07-19    188    177.2473     120.4169\nt+27 2020-07-20    209    188.2695     120.4292\nt+28 2020-07-21    217    181.8226     120.4403\nt+29 2020-07-22    229    193.0675     120.4505\nt+30 2020-07-23    219    186.3980     120.4598\nt+31 2020-07-24    221    197.8654     120.4683\nt+32 2020-07-25    215    190.9733     120.4761\nt+33 2020-07-26    195    202.6634     120.4833\nt+34 2020-07-27    216    195.5487     120.4898\nt+35 2020-07-28    212    207.4613     120.4959\nt+36 2020-07-29    235    200.1240     120.5015\nt+37 2020-07-30    196    212.2593     120.5066\nt+38 2020-07-31    226    204.6994     120.5114\nt+39 2020-08-01    197    217.0572     120.5158\nt+40 2020-08-02    216    209.2747     120.5199\nt+41 2020-08-03    208    221.8552     120.5237\nt+42 2020-08-04    215    213.8501     120.5272\nt+43 2020-08-05    212    226.6531     120.5305\nt+44 2020-08-06    185    218.4254     120.5336\nt+45 2020-08-07    174    231.4511     120.5364\nt+46 2020-08-08    156    223.0008     120.5391\nt+47 2020-08-09    132    236.2490     120.5416\nt+48 2020-08-10    163    227.5761     120.5440\nt+49 2020-08-11    189    241.0469     120.5462\nt+50 2020-08-12    184    232.1515     120.5483\nt+51 2020-08-13    188    245.8449     120.5503\nt+52 2020-08-14    174    236.7268     120.5522\nt+53 2020-08-15    169    250.6428     120.5539\n```\n\n\n:::\n:::\n\n\n\n:::\n\n::: {.content-visible when-format=\"html\"}\n\n\n\n::: {#tbl-forecastd .cell tbl-cap='Comparación de Resultados entre las técnicas y los datos reales para evaluar precisión'}\n::: {.cell-output-display}\n![](muertes_files/figure-epub/tbl-forecastd-1.png)\n:::\n:::\n\n\n\n:::\n\n::: {#fig-phwd}\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](muertes_files/figure-epub/unnamed-chunk-9-1.png)\n:::\n:::\n\n\n\n\nPronóstico obtenido mediante la técnica de Holt-Winters.\n:::\n\n::: {#fig-pmlpd}\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](muertes_files/figure-epub/unnamed-chunk-10-1.png)\n:::\n:::\n\n\n\n\nPronóstico obtenido mediante la red neuronal MLP.\n:::\n\n::: {style=\"text-align: justify\"}\nA través de las @fig-phwd y @fig-pmlpd, se observa que el pronóstico derivado de la técnica Holt-Winters muestra una mayor proximidad al comportamiento de la gráfica real.\n\nUtilizando las métricas RMSE, MAE y MAPE, se lleva a cabo la evaluación de la calidad o bondad de ajuste de los métodos empleados en este estudio con el fin de seleccionar el modelo más adecuado.\n:::\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n|                  |           |                |           |           |               |           |\n|------------------|:---------:|:--------------:|:---------:|:---------:|:-------------:|:---------:|\n|                  |           | ***Training*** |           |           | ***Testing*** |           |\n|                  | **RMSE**  |    **MAE**     | **MAPE**  | **RMSE**  |    **MAE**    | **MAPE**  |\n| **Holt-Winters** | *12.6365* |    *9.6103*    | *19.4096* | *34.0665* |   *25.5356*   | *12.9770* |\n| **MLP**          | *11.7584* |    *8.8446*    | *15.6144* | *67.2031* |   *59.7811*   | *49.0686* |\n\n: Errores de los modelos para casos confirmados. {#tbl-errd}\n\n::: {style=\"text-align: justify\"}\nLos resultados derivados de la tabla de errores (@tbl-errd) llevan a la conclusión de que, en esta base de datos específica, a pesar de que la red MLP exhibe errores más reducidos durante la fase de entrenamiento, la técnica de Holt-Winters presenta un error considerablemente menor en la etapa de prueba en comparación con MLP. Esto evidencia su mayor eficacia en la predicción realizada. Por consiguiente, se recomienda el uso del método Holt-Winters para llevar a cabo el pronóstico de los próximos 30 días.\n:::\n\n## Pronóstico de los próximos 30 días\n\n::: {.content-visible when-format=\"html\" style=\"text-align: justify\"}\nTras la identificación del modelo óptimo, se procedió a prever el comportamiento futuro de la serie temporal de casos de muerte para los próximos 30 días utilizando dicho modelo. Se elaboraron representaciones gráficas de la predicción de estos casos, realizando una comparación de la efectividad entre las implementaciones de redes neuronales en la paquetería de R y la paquetería nativa de Python, las cuales se encuentran en las figuras @fig-pronmuer y @fig-hwfinal, respectivamente.\n:::\n\n::: {.content-visible when-format=\"pdf\" style=\"text-align: justify\"}\nTras la identificación del modelo óptimo, se procedió a prever el comportamiento futuro de la serie temporal de casos de muerte para los próximos 30 días utilizando dicho modelo. Se elaboraron representaciones gráficas de la predicción de estos casos, realizando una comparación de la efectividad entre las implementaciones de redes neuronales en la paquetería de R y la paquetería nativa de Python, las cuales se encuentran en las figuras @fig-pronmuer y @fig-hwf1, respectivamente.\n:::\n\n### Implementación en R\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHW_deaths <- HoltWinters(ts(Deaths_df$Deaths,frequency = 2)) \nHW_for_d <- forecast(HW_deaths, h=30, level=c(80,95)) \n```\n:::\n\n\n\n\n::: {#fig-pronmuer}\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](muertes_files/figure-epub/unnamed-chunk-13-1.png)\n:::\n:::\n\n\n\n\nPredicción futura de la serie tiempo para decesos diarios mediante el modelo Holt-Winters.\n:::\n\n::: {.content-visible when-format=\"html\"}\n::: {style=\"text-align: justify\"}\nLos resultados del pronóstico indican que el 14 de septiembre de 2020 se proyectan 184 nuevos casos de muerte por COVID-19. Estos valores correspondientes al período de 30 días se detallan a continuación en la @tbl-pmuertes .\n:::\n:::\n\n::: {.content-visible when-format=\"pdf\"}\n::: {style=\"text-align: justify\"}\nLos resultados del pronóstico indican que el 14 de septiembre de 2020 se proyectan 184 nuevos casos de muerte por COVID-19. Estos valores correspondientes al período de 30 días se detallan a continuación en la @tbl-pmuertespdf .\n:::\n:::\n\n::: {.content-visible when-format=\"html\"}\n\n\n\n::: {#tbl-pmuertes .cell tbl-cap='Pronóstico de decesos por COVID-19 en Irán en los próximos 30 días'}\n::: {.cell-output-display}\n![](muertes_files/figure-epub/tbl-pmuertes-1.png)\n:::\n:::\n\n\n\n:::\n\n::: {.content-visible when-format=\"pdf\"}\n\n\n\n::: {#tbl-pmuertespdf .cell tbl-cap='Pronóstico de decesos por COVID-19 en Irán en los próximos 30 días'}\n::: {.cell-output .cell-output-stdout}\n\n```\n        Fecha  Decesos\n1  2020-08-16 174.0023\n2  2020-08-17 172.7223\n3  2020-08-18 174.8375\n4  2020-08-19 173.5575\n5  2020-08-20 175.6728\n6  2020-08-21 174.3927\n7  2020-08-22 176.5080\n8  2020-08-23 175.2279\n9  2020-08-24 177.3432\n10 2020-08-25 176.0631\n11 2020-08-26 178.1784\n12 2020-08-27 176.8983\n13 2020-08-28 179.0136\n14 2020-08-29 177.7335\n15 2020-08-30 179.8488\n16 2020-08-31 178.5688\n17 2020-09-01 180.6840\n18 2020-09-02 179.4040\n19 2020-09-03 181.5192\n20 2020-09-04 180.2392\n21 2020-09-05 182.3545\n22 2020-09-06 181.0744\n23 2020-09-07 183.1897\n24 2020-09-08 181.9096\n25 2020-09-09 184.0249\n26 2020-09-10 182.7448\n27 2020-09-11 184.8601\n28 2020-09-12 183.5800\n29 2020-09-13 185.6953\n30 2020-09-14 184.4152\n```\n\n\n:::\n:::\n\n\n\n:::\n\n### Implementación en Python\n\n::: {.callout-warning collapse=\"true\" icon=\"false\"}\n#### ▸Código\n\n``` python\nimport numpy as np \nimport pandas as pd \nimport plotly.express as px \nfrom statsmodels.tsa.holtwinters import ExponentialSmoothing\n\n# Importación de los datos de CASOS DE MUERTE del 20-02 al 15-08-2020\ndata = pd.read_excel('muertes.xlsx')\ndf = pd.DataFrame(data)\n\n# Configurar el modelo Holt-Winters\nmodel = ExponentialSmoothing(df['Deaths'], trend='add', \nseasonal='add',seasonal_periods=14)\nmodel_fit = model.fit(optimized=True)\n\n# Generar predicciones\nforecast_days = 30  # Número de días a predecir\nforecast = model_fit.forecast(steps=forecast_days)\n\n# Crear un DataFrame con las fechas de predicción\nforecast_dates = pd.date_range(start=df['Date'].max() + \npd.Timedelta(days=1), periods=forecast_days, freq='D')\n\n# Agregar las fechas y valores predichos al DataFrame original\nforecast_df = pd.DataFrame({'Date': forecast_dates, \n'Forecast': forecast})\ndf_t = pd.concat([df, forecast_df])\n\n# Crear una gráfica interactiva con Plotly\nfig = px.line(df, x='Date', y='Deaths',title='Holt-Winters Forecast', \nlabels={'Deaths': 'Deaths'})\nfig.add_scatter(x=forecast_dates, y=forecast, mode='lines', \nname='Forecast', line=dict(color='red'))\nfig.show()\n```\n:::\n\n::: {.content-visible when-format=\"html\"}\n\n\n\n\n\n::: {.cell}\n::: {#fig-hwfinal .cell-output-display}\n\n```{=html}\n<div>                        <script type=\"text/javascript\">window.PlotlyConfig = {MathJaxConfig: 'local'};</script>\n        <script charset=\"utf-8\" src=\"https://cdn.plot.ly/plotly-2.27.0.min.js\"></script>                <div id=\"ed7ec6fc-3369-4e67-8d6f-74dd75e02a91\" class=\"plotly-graph-div\" style=\"height:100%; width:100%;\"></div>            <script type=\"text/javascript\">                                    window.PLOTLYENV=window.PLOTLYENV || {};                                    if (document.getElementById(\"ed7ec6fc-3369-4e67-8d6f-74dd75e02a91\")) {                    Plotly.newPlot(                        \"ed7ec6fc-3369-4e67-8d6f-74dd75e02a91\",                        [{\"hovertemplate\":\"Date=%{x}\\u003cbr\\u003eDeaths=%{y}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"legendgroup\":\"\",\"line\":{\"color\":\"#636efa\",\"dash\":\"solid\"},\"marker\":{\"symbol\":\"circle\"},\"mode\":\"lines\",\"name\":\"\",\"orientation\":\"v\",\"showlegend\":false,\"x\":[\"2020-02-20T00:00:00\",\"2020-02-21T00:00:00\",\"2020-02-22T00:00:00\",\"2020-02-23T00:00:00\",\"2020-02-24T00:00:00\",\"2020-02-25T00:00:00\",\"2020-02-26T00:00:00\",\"2020-02-27T00:00:00\",\"2020-02-28T00:00:00\",\"2020-02-29T00:00:00\",\"2020-03-01T00:00:00\",\"2020-03-02T00:00:00\",\"2020-03-03T00:00:00\",\"2020-03-04T00:00:00\",\"2020-03-05T00:00:00\",\"2020-03-06T00:00:00\",\"2020-03-07T00:00:00\",\"2020-03-08T00:00:00\",\"2020-03-09T00:00:00\",\"2020-03-10T00:00:00\",\"2020-03-11T00:00:00\",\"2020-03-12T00:00:00\",\"2020-03-13T00:00:00\",\"2020-03-14T00:00:00\",\"2020-03-15T00:00:00\",\"2020-03-16T00:00:00\",\"2020-03-17T00:00:00\",\"2020-03-18T00:00:00\",\"2020-03-19T00:00:00\",\"2020-03-20T00:00:00\",\"2020-03-21T00:00:00\",\"2020-03-22T00:00:00\",\"2020-03-23T00:00:00\",\"2020-03-24T00:00:00\",\"2020-03-25T00:00:00\",\"2020-03-26T00:00:00\",\"2020-03-27T00:00:00\",\"2020-03-28T00:00:00\",\"2020-03-29T00:00:00\",\"2020-03-30T00:00:00\",\"2020-03-31T00:00:00\",\"2020-04-01T00:00:00\",\"2020-04-02T00:00:00\",\"2020-04-03T00:00:00\",\"2020-04-04T00:00:00\",\"2020-04-05T00:00:00\",\"2020-04-06T00:00:00\",\"2020-04-07T00:00:00\",\"2020-04-08T00:00:00\",\"2020-04-09T00:00:00\",\"2020-04-10T00:00:00\",\"2020-04-11T00:00:00\",\"2020-04-12T00:00:00\",\"2020-04-13T00:00:00\",\"2020-04-14T00:00:00\",\"2020-04-15T00:00:00\",\"2020-04-16T00:00:00\",\"2020-04-17T00:00:00\",\"2020-04-18T00:00:00\",\"2020-04-19T00:00:00\",\"2020-04-20T00:00:00\",\"2020-04-21T00:00:00\",\"2020-04-22T00:00:00\",\"2020-04-23T00:00:00\",\"2020-04-24T00:00:00\",\"2020-04-25T00:00:00\",\"2020-04-26T00:00:00\",\"2020-04-27T00:00:00\",\"2020-04-28T00:00:00\",\"2020-04-29T00:00:00\",\"2020-04-30T00:00:00\",\"2020-05-01T00:00:00\",\"2020-05-02T00:00:00\",\"2020-05-03T00:00:00\",\"2020-05-04T00:00:00\",\"2020-05-05T00:00:00\",\"2020-05-06T00:00:00\",\"2020-05-07T00:00:00\",\"2020-05-08T00:00:00\",\"2020-05-09T00:00:00\",\"2020-05-10T00:00:00\",\"2020-05-11T00:00:00\",\"2020-05-12T00:00:00\",\"2020-05-13T00:00:00\",\"2020-05-14T00:00:00\",\"2020-05-15T00:00:00\",\"2020-05-16T00:00:00\",\"2020-05-17T00:00:00\",\"2020-05-18T00:00:00\",\"2020-05-19T00:00:00\",\"2020-05-20T00:00:00\",\"2020-05-21T00:00:00\",\"2020-05-22T00:00:00\",\"2020-05-23T00:00:00\",\"2020-05-24T00:00:00\",\"2020-05-25T00:00:00\",\"2020-05-26T00:00:00\",\"2020-05-27T00:00:00\",\"2020-05-28T00:00:00\",\"2020-05-29T00:00:00\",\"2020-05-30T00:00:00\",\"2020-05-31T00:00:00\",\"2020-06-01T00:00:00\",\"2020-06-02T00:00:00\",\"2020-06-03T00:00:00\",\"2020-06-04T00:00:00\",\"2020-06-05T00:00:00\",\"2020-06-06T00:00:00\",\"2020-06-07T00:00:00\",\"2020-06-08T00:00:00\",\"2020-06-09T00:00:00\",\"2020-06-10T00:00:00\",\"2020-06-11T00:00:00\",\"2020-06-12T00:00:00\",\"2020-06-13T00:00:00\",\"2020-06-14T00:00:00\",\"2020-06-15T00:00:00\",\"2020-06-16T00:00:00\",\"2020-06-17T00:00:00\",\"2020-06-18T00:00:00\",\"2020-06-19T00:00:00\",\"2020-06-20T00:00:00\",\"2020-06-21T00:00:00\",\"2020-06-22T00:00:00\",\"2020-06-23T00:00:00\",\"2020-06-24T00:00:00\",\"2020-06-25T00:00:00\",\"2020-06-26T00:00:00\",\"2020-06-27T00:00:00\",\"2020-06-28T00:00:00\",\"2020-06-29T00:00:00\",\"2020-06-30T00:00:00\",\"2020-07-01T00:00:00\",\"2020-07-02T00:00:00\",\"2020-07-03T00:00:00\",\"2020-07-04T00:00:00\",\"2020-07-05T00:00:00\",\"2020-07-06T00:00:00\",\"2020-07-07T00:00:00\",\"2020-07-08T00:00:00\",\"2020-07-09T00:00:00\",\"2020-07-10T00:00:00\",\"2020-07-11T00:00:00\",\"2020-07-12T00:00:00\",\"2020-07-13T00:00:00\",\"2020-07-14T00:00:00\",\"2020-07-15T00:00:00\",\"2020-07-16T00:00:00\",\"2020-07-17T00:00:00\",\"2020-07-18T00:00:00\",\"2020-07-19T00:00:00\",\"2020-07-20T00:00:00\",\"2020-07-21T00:00:00\",\"2020-07-22T00:00:00\",\"2020-07-23T00:00:00\",\"2020-07-24T00:00:00\",\"2020-07-25T00:00:00\",\"2020-07-26T00:00:00\",\"2020-07-27T00:00:00\",\"2020-07-28T00:00:00\",\"2020-07-29T00:00:00\",\"2020-07-30T00:00:00\",\"2020-07-31T00:00:00\",\"2020-08-01T00:00:00\",\"2020-08-02T00:00:00\",\"2020-08-03T00:00:00\",\"2020-08-04T00:00:00\",\"2020-08-05T00:00:00\",\"2020-08-06T00:00:00\",\"2020-08-07T00:00:00\",\"2020-08-08T00:00:00\",\"2020-08-09T00:00:00\",\"2020-08-10T00:00:00\",\"2020-08-11T00:00:00\",\"2020-08-12T00:00:00\",\"2020-08-13T00:00:00\",\"2020-08-14T00:00:00\",\"2020-08-15T00:00:00\"],\"xaxis\":\"x\",\"y\":[2.0,2.0,2.0,1.0,3.0,4.0,3.0,7.0,12.0,9.0,10.0,11.0,23.0,15.0,15.0,17.0,21.0,49.0,43.0,54.0,63.0,75.0,85.0,94.0,116.0,129.0,135.0,147.0,149.0,149.0,123.0,129.0,127.0,122.0,143.0,157.0,144.0,139.0,123.0,117.0,141.0,138.0,124.0,134.0,158.0,154.5,151.0,136.0,133.0,121.0,117.0,122.0,125.0,117.0,111.0,98.0,94.0,92.0,89.0,73.0,87.0,91.0,88.0,94.0,90.0,93.0,76.0,60.0,96.0,71.0,80.0,71.0,63.0,65.0,47.0,74.0,63.0,78.0,68.0,55.0,48.0,51.0,45.0,48.0,50.0,71.0,48.0,35.0,51.0,69.0,62.0,64.0,66.0,51.0,59.0,58.0,34.0,57.0,56.0,63.0,50.0,57.0,63.0,81.0,64.0,70.0,59.0,63.0,75.0,72.0,70.0,74.0,81.0,78.0,75.0,71.0,107.0,113.0,115.0,120.0,87.0,120.0,115.0,116.0,119.0,121.0,133.0,134.0,109.0,125.0,144.0,162.0,147.0,141.0,148.0,154.0,148.0,163.0,160.0,200.0,153.0,221.0,142.0,188.0,194.0,203.0,179.0,199.0,198.0,183.0,188.0,209.0,217.0,229.0,219.0,221.0,215.0,195.0,216.0,212.0,235.0,196.0,226.0,197.0,216.0,208.0,215.0,212.0,185.0,174.0,156.0,132.0,163.0,189.0,184.0,188.0,174.0,169.0],\"yaxis\":\"y\",\"type\":\"scatter\"},{\"line\":{\"color\":\"red\"},\"mode\":\"lines\",\"name\":\"Forecast\",\"x\":[\"2020-08-16T00:00:00\",\"2020-08-17T00:00:00\",\"2020-08-18T00:00:00\",\"2020-08-19T00:00:00\",\"2020-08-20T00:00:00\",\"2020-08-21T00:00:00\",\"2020-08-22T00:00:00\",\"2020-08-23T00:00:00\",\"2020-08-24T00:00:00\",\"2020-08-25T00:00:00\",\"2020-08-26T00:00:00\",\"2020-08-27T00:00:00\",\"2020-08-28T00:00:00\",\"2020-08-29T00:00:00\",\"2020-08-30T00:00:00\",\"2020-08-31T00:00:00\",\"2020-09-01T00:00:00\",\"2020-09-02T00:00:00\",\"2020-09-03T00:00:00\",\"2020-09-04T00:00:00\",\"2020-09-05T00:00:00\",\"2020-09-06T00:00:00\",\"2020-09-07T00:00:00\",\"2020-09-08T00:00:00\",\"2020-09-09T00:00:00\",\"2020-09-10T00:00:00\",\"2020-09-11T00:00:00\",\"2020-09-12T00:00:00\",\"2020-09-13T00:00:00\",\"2020-09-14T00:00:00\"],\"y\":[169.907256798666,168.60006317661296,170.90733448364597,172.33373546711675,164.40717176219715,168.70776945548218,152.83485839444123,152.34741986783843,159.42316140080524,165.9292362680337,161.36021834716738,161.50703690827086,156.5877420801,152.46848143812673,151.86035502620388,150.55316140415084,152.86043271118385,154.28683369465463,146.36026998973503,150.66086768302006,134.7879566219791,134.3005180953763,141.37625962834312,147.88233449557157,143.31331657470525,143.4601351358087,138.5408403076379,134.4215796656646,133.81345325374176,132.5062596316887],\"type\":\"scatter\"}],                        {\"template\":{\"data\":{\"histogram2dcontour\":[{\"type\":\"histogram2dcontour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"choropleth\":[{\"type\":\"choropleth\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"histogram2d\":[{\"type\":\"histogram2d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"heatmap\":[{\"type\":\"heatmap\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"heatmapgl\":[{\"type\":\"heatmapgl\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"contourcarpet\":[{\"type\":\"contourcarpet\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"contour\":[{\"type\":\"contour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"surface\":[{\"type\":\"surface\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"mesh3d\":[{\"type\":\"mesh3d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"scatter\":[{\"fillpattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2},\"type\":\"scatter\"}],\"parcoords\":[{\"type\":\"parcoords\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolargl\":[{\"type\":\"scatterpolargl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"bar\":[{\"error_x\":{\"color\":\"#2a3f5f\"},\"error_y\":{\"color\":\"#2a3f5f\"},\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"bar\"}],\"scattergeo\":[{\"type\":\"scattergeo\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolar\":[{\"type\":\"scatterpolar\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"histogram\":[{\"marker\":{\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"histogram\"}],\"scattergl\":[{\"type\":\"scattergl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatter3d\":[{\"type\":\"scatter3d\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermapbox\":[{\"type\":\"scattermapbox\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterternary\":[{\"type\":\"scatterternary\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattercarpet\":[{\"type\":\"scattercarpet\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"carpet\":[{\"aaxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"baxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"type\":\"carpet\"}],\"table\":[{\"cells\":{\"fill\":{\"color\":\"#EBF0F8\"},\"line\":{\"color\":\"white\"}},\"header\":{\"fill\":{\"color\":\"#C8D4E3\"},\"line\":{\"color\":\"white\"}},\"type\":\"table\"}],\"barpolar\":[{\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"barpolar\"}],\"pie\":[{\"automargin\":true,\"type\":\"pie\"}]},\"layout\":{\"autotypenumbers\":\"strict\",\"colorway\":[\"#636efa\",\"#EF553B\",\"#00cc96\",\"#ab63fa\",\"#FFA15A\",\"#19d3f3\",\"#FF6692\",\"#B6E880\",\"#FF97FF\",\"#FECB52\"],\"font\":{\"color\":\"#2a3f5f\"},\"hovermode\":\"closest\",\"hoverlabel\":{\"align\":\"left\"},\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"#E5ECF6\",\"polar\":{\"bgcolor\":\"#E5ECF6\",\"angularaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"radialaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"ternary\":{\"bgcolor\":\"#E5ECF6\",\"aaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"baxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"caxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"coloraxis\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"colorscale\":{\"sequential\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"sequentialminus\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"diverging\":[[0,\"#8e0152\"],[0.1,\"#c51b7d\"],[0.2,\"#de77ae\"],[0.3,\"#f1b6da\"],[0.4,\"#fde0ef\"],[0.5,\"#f7f7f7\"],[0.6,\"#e6f5d0\"],[0.7,\"#b8e186\"],[0.8,\"#7fbc41\"],[0.9,\"#4d9221\"],[1,\"#276419\"]]},\"xaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"yaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"scene\":{\"xaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"yaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"zaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2}},\"shapedefaults\":{\"line\":{\"color\":\"#2a3f5f\"}},\"annotationdefaults\":{\"arrowcolor\":\"#2a3f5f\",\"arrowhead\":0,\"arrowwidth\":1},\"geo\":{\"bgcolor\":\"white\",\"landcolor\":\"#E5ECF6\",\"subunitcolor\":\"white\",\"showland\":true,\"showlakes\":true,\"lakecolor\":\"white\"},\"title\":{\"x\":0.05},\"mapbox\":{\"style\":\"light\"}}},\"xaxis\":{\"anchor\":\"y\",\"domain\":[0.0,1.0],\"title\":{\"text\":\"Date\"}},\"yaxis\":{\"anchor\":\"x\",\"domain\":[0.0,1.0],\"title\":{\"text\":\"Deaths\"}},\"legend\":{\"tracegroupgap\":0},\"title\":{\"text\":\"Holt-Winters Forecast\"}},                        {\"responsive\": true}                    )                };                            </script>        </div>\n```\n\n\nPronóstico de casos de muerte por COVID-19 en Irán en los próximos 30 días (implementación en Python)\n:::\n:::\n\n\n\n:::\n\n::: {.content-visible when-format=\"pdf\"}\n![Pronóstico de casos de muerte por COVID-19 en Irán en los próximos 30 días (implementación en Python)](Imagenes/Muertes.png){#fig-hwf1 fig-align=\"center\"}\n:::\n\n::: {.content-visible when-format=\"html\"}\n::: {style=\"text-align: justify\"}\nLos resultados del pronóstico en la @fig-hwfinal indican que el 14 de septiembre de 2020 se proyectan aproximadamente 132 nuevos casos de muerte por COVID-19.\n:::\n:::\n\n::: {.content-visible when-format=\"pdf\"}\n::: {style=\"text-align: justify\"}\nLos resultados del pronóstico en la @fig-hwf1 indican que el 14 de septiembre de 2020 se proyectan aproximadamente 132 nuevos casos de muerte por COVID-19.\n:::\n:::\n",
    "supporting": [
      "muertes_files\\figure-epub"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}