{
  "hash": "3d0660e782831bb9a13a1f058322e60e",
  "result": {
    "engine": "knitr",
    "markdown": "---\nlang: es\n---\n\n\n\n\n\n# Pronóstico de decesos diarios\n\n::: {.content-visible when-format=\"html\"}\n::: {style=\"text-align: justify\"}\nDe manera similar a la evaluación llevada a cabo en la base de datos de los casos confirmados de COVID-19 en Irán, se ejecutó un análisis para los datos de muertes por COVID-19 en Irán, abarcando el mismo período temporal, desde el 20 de febrero hasta el 15 de agosto de 2020. El propósito fue determinar si, de forma análoga, la red neuronal MLP demuestra un mejor ajuste a los datos en comparación con la técnica de series temporales Holt-Winters, o si, en este caso particular, la técnica Holt-Winters ofrece una mayor precisión.\n\nEs relevante señalar la presencia de datos faltantes para las fechas 21 de febrero, 1 de marzo y 5 de mayo de 2020 en el conjunto de datos. Por consiguiente, al igual que en los casos confirmados, se procedió con una interpolación promedio para sustituir dichos datos faltantes. La @fig-muertes exhibe la serie temporal resultante luego de estas correcciones.\n:::\n:::\n\n::: {.content-visible when-format=\"pdf\"}\n::: {style=\"text-align: justify\"}\nDe manera similar a la evaluación llevada a cabo en la base de datos de los casos confirmados de COVID-19 en Irán, se ejecutó un análisis para los datos de muertes por COVID-19 en Irán, abarcando el mismo período temporal, desde el 20 de febrero hasta el 15 de agosto de 2020. El propósito fue determinar si, de forma análoga, la red neuronal MLP demuestra un mejor ajuste a los datos en comparación con la técnica de series temporales Holt-Winters, o si, en este caso particular, la técnica Holt-Winters ofrece una mayor precisión.\n\nEs relevante señalar la presencia de datos faltantes para las fechas 21 de febrero, 1 de marzo y 5 de mayo de 2020 en el conjunto de datos. Por consiguiente, al igual que en los casos confirmados, se procedió con una interpolación promedio para sustituir dichos datos faltantes. La @fig-muertespdf exhibe la serie temporal resultante luego de estas correcciones.\n:::\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.content-visible when-format=\"html\"}\n::: {#fig-muertes}\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](muertes_files/figure-pdf/unnamed-chunk-3-1.pdf)\n:::\n:::\n\n\n\n\n\nSerie de tiempo de los casos de muerte por COVID-19 en Irán del 20-02-2020 al 15-08-2020.\n:::\n:::\n\n::: {.content-visible when-format=\"pdf\"}\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Serie de tiempo de los casos de muerte por COVID-19 en Irán del 20-02-2020 al 15-08-2020.](muertes_files/figure-pdf/fig-muertespdf-1.pdf){#fig-muertespdf}\n:::\n:::\n\n\n\n\n:::\n\n## Pronóstico, comparación y métricas de rendimiento\n\n::: {style=\"text-align: justify\"}\nLa evaluación del desempeño de los métodos se realiza a través de la separación del conjunto de datos en entrenamiento y prueba. El set inicial, compuesto por el $70\\%$ de los datos, se emplea para el entrenamiento de los modelos, mientras que el $30\\%$ restante se reservará para llevar a cabo las pruebas pertinentes.\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nDeaths_ts <- ts(Deaths_ts,frequency=1) \ntsize <- round(0.7 * nrow(Deaths_df)) \ntrain_deaths <- window(Deaths_ts,end=tsize) \ntest_deaths <- window(Deaths_ts,start=tsize+1)\n```\n:::\n\n\n\n\n\n::: {style=\"text-align: justify\"}\nCon el propósito de llevar a cabo un análisis cuantitativo exhaustivo, se presenta a continuación una tabla comparativa de los resultados derivados de las dos técnicas implementadas (después de realizar el entrenamiento, modelado y pronóstico), y la base de datos de prueba. Posteriormente, se exhiben gráficas representativas de estos resultados. En la @fig-phwd se muestra el pronóstico mediante Holt-Winters acompañado de su respectivo intervalo de confianza. En contraste, en la @fig-pmlpd, la gráfica punteada en color rojo representa el comportamiento real de los datos, mientras que en azul se representa el pronóstico obtenido a través de la red MLP.\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.content-visible when-format=\"pdf\"}\n\n\n\n\n::: {#tbl-forecastdpdf .cell tbl-cap='Comparación de Resultados entre las técnicas y los datos reales para evaluar precisión.'}\n::: {.cell-output .cell-output-stdout}\n\n```\n           Date Deaths Forecast_HW Forecast_MLP\nt+1  2020-06-24    121    125.8962     118.6604\nt+2  2020-06-25    133    122.3430     118.6508\nt+3  2020-06-26    134    130.6941     118.6858\nt+4  2020-06-27    109    126.9184     118.7546\nt+5  2020-06-28    125    135.4921     118.8098\nt+6  2020-06-29    144    131.4938     118.8626\nt+7  2020-06-30    162    140.2900     118.9109\nt+8  2020-07-01    147    136.0691     118.9555\nt+9  2020-07-02    141    145.0880     118.9965\nt+10 2020-07-03    148    140.6445     119.0344\nt+11 2020-07-04    154    149.8859     119.0693\nt+12 2020-07-05    148    145.2198     119.1014\nt+13 2020-07-06    163    154.6839     119.1310\nt+14 2020-07-07    160    149.7952     119.1583\nt+15 2020-07-08    200    159.4818     119.1835\nt+16 2020-07-09    153    154.3705     119.2066\nt+17 2020-07-10    221    164.2798     119.2279\nt+18 2020-07-11    142    158.9459     119.2475\nt+19 2020-07-12    188    169.0777     119.2656\nt+20 2020-07-13    194    163.5212     119.2823\nt+21 2020-07-14    203    173.8757     119.2976\nt+22 2020-07-15    179    168.0966     119.3117\nt+23 2020-07-16    199    178.6736     119.3247\nt+24 2020-07-17    198    172.6719     119.3366\nt+25 2020-07-18    183    183.4716     119.3477\nt+26 2020-07-19    188    177.2473     119.3578\nt+27 2020-07-20    209    188.2695     119.3671\nt+28 2020-07-21    217    181.8226     119.3757\nt+29 2020-07-22    229    193.0675     119.3836\nt+30 2020-07-23    219    186.3980     119.3909\nt+31 2020-07-24    221    197.8654     119.3976\nt+32 2020-07-25    215    190.9733     119.4037\nt+33 2020-07-26    195    202.6634     119.4094\nt+34 2020-07-27    216    195.5487     119.4146\nt+35 2020-07-28    212    207.4613     119.4194\nt+36 2020-07-29    235    200.1240     119.4239\nt+37 2020-07-30    196    212.2593     119.4279\nt+38 2020-07-31    226    204.6994     119.4317\nt+39 2020-08-01    197    217.0572     119.4351\nt+40 2020-08-02    216    209.2747     119.4383\nt+41 2020-08-03    208    221.8552     119.4412\nt+42 2020-08-04    215    213.8501     119.4439\nt+43 2020-08-05    212    226.6531     119.4464\nt+44 2020-08-06    185    218.4254     119.4486\nt+45 2020-08-07    174    231.4511     119.4507\nt+46 2020-08-08    156    223.0008     119.4527\nt+47 2020-08-09    132    236.2490     119.4544\nt+48 2020-08-10    163    227.5761     119.4561\nt+49 2020-08-11    189    241.0469     119.4576\nt+50 2020-08-12    184    232.1515     119.4590\nt+51 2020-08-13    188    245.8449     119.4602\nt+52 2020-08-14    174    236.7268     119.4614\nt+53 2020-08-15    169    250.6428     119.4625\n```\n\n\n:::\n:::\n\n\n\n\n:::\n\n::: {.content-visible when-format=\"html\"}\n\n\n\n\n::: {#tbl-forecastd .cell tbl-cap='Comparación de Resultados entre las técnicas y los datos reales para evaluar precisión'}\n::: {.cell-output-display}\n![](muertes_files/figure-pdf/tbl-forecastd-1.pdf)\n:::\n:::\n\n\n\n\n:::\n\n::: {#fig-phwd}\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](muertes_files/figure-pdf/unnamed-chunk-9-1.pdf)\n:::\n:::\n\n\n\n\n\nPronóstico obtenido mediante la técnica de Holt-Winters.\n:::\n\n::: {#fig-pmlpd}\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](muertes_files/figure-pdf/unnamed-chunk-10-1.pdf)\n:::\n:::\n\n\n\n\n\nPronóstico obtenido mediante la red neuronal MLP.\n:::\n\n::: {style=\"text-align: justify\"}\nA través de las @fig-phwd y @fig-pmlpd, se observa que el pronóstico derivado de la técnica Holt-Winters muestra una mayor proximidad al comportamiento de la gráfica real.\n\nUtilizando las métricas RMSE, MAE y MAPE, se lleva a cabo la evaluación de la calidad o bondad de ajuste de los métodos empleados en este estudio con el fin de seleccionar el modelo más adecuado.\n:::\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n|                  |           |                |           |           |               |           |\n|-----------|:---------:|:---------:|:---------:|:---------:|:---------:|:---------:|\n|                  |           | ***Training*** |           |           | ***Testing*** |           |\n|                  | **RMSE**  |    **MAE**     | **MAPE**  | **RMSE**  |    **MAE**    | **MAPE**  |\n| **Holt-Winters** | *12.6365* |    *9.6103*    | *19.4096* | *34.0665* |   *25.5356*   | *12.9770* |\n| **MLP**          | *11.7584* |    *8.8446*    | *15.6144* | *67.2031* |   *59.7811*   | *49.0686* |\n\n: Errores de los modelos para casos confirmados. {#tbl-errd}\n\n::: {style=\"text-align: justify\"}\nLos resultados derivados de la tabla de errores (@tbl-errd) llevan a la conclusión de que, en esta base de datos específica, a pesar de que la red MLP exhibe errores más reducidos durante la fase de entrenamiento, la técnica de Holt-Winters presenta un error considerablemente menor en la etapa de prueba en comparación con MLP. Esto evidencia su mayor eficacia en la predicción realizada. Por consiguiente, se recomienda el uso del método Holt-Winters para llevar a cabo el pronóstico de los próximos 30 días.\n:::\n\n## Pronóstico de los próximos 30 días\n\n::: {.content-visible when-format=\"html\" style=\"text-align: justify\"}\nTras la identificación del modelo óptimo, se procedió a prever el comportamiento futuro de la serie temporal de casos de muerte para los próximos 30 días utilizando dicho modelo. Se elaboraron representaciones gráficas de la predicción de estos casos, realizando una comparación de la efectividad entre las implementaciones de redes neuronales en la paquetería de R y la paquetería nativa de Python, las cuales se encuentran en las figuras @fig-pronmuer y @fig-hwfinal, respectivamente.\n:::\n\n::: {.content-visible when-format=\"pdf\" style=\"text-align: justify\"}\nTras la identificación del modelo óptimo, se procedió a prever el comportamiento futuro de la serie temporal de casos de muerte para los próximos 30 días utilizando dicho modelo. Se elaboraron representaciones gráficas de la predicción de estos casos, realizando una comparación de la efectividad entre las implementaciones de redes neuronales en la paquetería de R y la paquetería nativa de Python, las cuales se encuentran en las figuras @fig-pronmuer y @fig-hwf1, respectivamente.\n:::\n\n### Implementación en R\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHW_deaths <- HoltWinters(ts(Deaths_df$Deaths,frequency = 2)) \nHW_for_d <- forecast(HW_deaths, h=30, level=c(80,95)) \n```\n:::\n\n\n\n\n\n::: {#fig-pronmuer}\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](muertes_files/figure-pdf/unnamed-chunk-13-1.pdf)\n:::\n:::\n\n\n\n\n\nPredicción futura de la serie tiempo para decesos diarios mediante el modelo Holt-Winters.\n:::\n\n::: {.content-visible when-format=\"html\"}\n::: {style=\"text-align: justify\"}\nLos resultados del pronóstico indican que, el 14 de septiembre de 2020, se proyectan 184 nuevos casos de muerte por COVID-19. Estos valores correspondientes al período de 30 días se detallan a continuación en la @tbl-pmuertes .\n:::\n:::\n\n::: {.content-visible when-format=\"pdf\"}\n::: {style=\"text-align: justify\"}\nLos resultados del pronóstico indican que, el 14 de septiembre de 2020, se proyectan 184 nuevos casos de muerte por COVID-19. Estos valores correspondientes al período de 30 días se detallan a continuación en la @tbl-pmuertespdf .\n:::\n:::\n\n::: {.content-visible when-format=\"html\"}\n\n\n\n\n::: {#tbl-pmuertes .cell tbl-cap='Pronóstico de decesos por COVID-19 en Irán en los próximos 30 días.'}\n::: {.cell-output-display}\n![](muertes_files/figure-pdf/tbl-pmuertes-1.pdf)\n:::\n:::\n\n\n\n\n:::\n\n::: {.content-visible when-format=\"pdf\"}\n\n\n\n\n::: {#tbl-pmuertespdf .cell tbl-cap='Pronóstico de decesos por COVID-19 en Irán en los próximos 30 días.'}\n::: {.cell-output .cell-output-stdout}\n\n```\n        Fecha  Decesos\n1  2020-08-16 174.0023\n2  2020-08-17 172.7223\n3  2020-08-18 174.8375\n4  2020-08-19 173.5575\n5  2020-08-20 175.6728\n6  2020-08-21 174.3927\n7  2020-08-22 176.5080\n8  2020-08-23 175.2279\n9  2020-08-24 177.3432\n10 2020-08-25 176.0631\n11 2020-08-26 178.1784\n12 2020-08-27 176.8983\n13 2020-08-28 179.0136\n14 2020-08-29 177.7335\n15 2020-08-30 179.8488\n16 2020-08-31 178.5688\n17 2020-09-01 180.6840\n18 2020-09-02 179.4040\n19 2020-09-03 181.5192\n20 2020-09-04 180.2392\n21 2020-09-05 182.3545\n22 2020-09-06 181.0744\n23 2020-09-07 183.1897\n24 2020-09-08 181.9096\n25 2020-09-09 184.0249\n26 2020-09-10 182.7448\n27 2020-09-11 184.8601\n28 2020-09-12 183.5800\n29 2020-09-13 185.6953\n30 2020-09-14 184.4152\n```\n\n\n:::\n:::\n\n\n\n\n:::\n\n### Implementación en Python\n\n::: {.callout-warning collapse=\"true\" icon=\"false\"}\n#### ▸Código\n\n``` python\nimport numpy as np \nimport pandas as pd \nimport plotly.express as px \nfrom statsmodels.tsa.holtwinters import ExponentialSmoothing\n\n# Importación de los datos de CASOS DE MUERTE del 20-02 al 15-08-2020\ndata = pd.read_excel('muertes.xlsx')\ndf = pd.DataFrame(data)\n\n# Configurar el modelo Holt-Winters\nmodel = ExponentialSmoothing(df['Deaths'], trend='add', \nseasonal='add',seasonal_periods=14)\nmodel_fit = model.fit(optimized=True)\n\n# Generar predicciones\nforecast_days = 30  # Número de días a predecir\nforecast = model_fit.forecast(steps=forecast_days)\n\n# Crear un DataFrame con las fechas de predicción\nforecast_dates = pd.date_range(start=df['Date'].max() + \npd.Timedelta(days=1), periods=forecast_days, freq='D')\n\n# Agregar las fechas y valores predichos al DataFrame original\nforecast_df = pd.DataFrame({'Date': forecast_dates, \n'Forecast': forecast})\ndf_t = pd.concat([df, forecast_df])\n\n# Crear una gráfica interactiva con Plotly\nfig = px.line(df, x='Date', y='Deaths',title='Holt-Winters Forecast', \nlabels={'Deaths': 'Deaths'})\nfig.add_scatter(x=forecast_dates, y=forecast, mode='lines', \nname='Forecast', line=dict(color='red'))\nfig.show()\n```\n:::\n\n::: {.content-visible when-format=\"html\"}\n\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n:::\n\n::: {.content-visible when-format=\"pdf\"}\n![Pronóstico de casos de muerte por COVID-19 en Irán en los próximos 30 días (implementación en Python).](Imagenes/Muertes.png){#fig-hwf1 fig-align=\"center\"}\n:::\n\n::: {.content-visible when-format=\"html\"}\n::: {style=\"text-align: justify\"}\nLos resultados del pronóstico en la @fig-hwfinal indican que, el 14 de septiembre de 2020, se proyectan aproximadamente 132 nuevos casos de muerte por COVID-19.\n:::\n:::\n\n::: {.content-visible when-format=\"pdf\"}\n::: {style=\"text-align: justify\"}\nLos resultados del pronóstico en la @fig-hwf1 indican que, el 14 de septiembre de 2020, se proyectan aproximadamente 132 nuevos casos de muerte por COVID-19.\n:::\n:::\n",
    "supporting": [
      "muertes_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}