project:
  type: book
  output-dir: docs

website:
  favicon: FCFMLOGO.png
  reader-mode: true
  search:
    location: sidebar
    type: overlay
  comments:
    hypothesis:
      theme: clean
      openSidebar: true

book:
  title: "Avances de tesis"
  author: "Jennifer Sherlyn López García"
  date: "07/14/2023"
  output-file: "avances-tesis"
  image: FCFMLOGO.png
  cover-image: FCFMLOGO.png
  sharing: [twitter, facebook]
  downloads: [pdf, epub]
  favicon: FCFMLOGO.png
  sidebar:
    logo: FCFMLOGO.png
    style: floating
    collapse-level: 1
    border: true
    search: true
  open-graph: true
  twitter-card: true
  site-url: httpss://example.com
  repo-actions: [edit, issue, source]
  repo-subdir: book
  chapters:
    - index.qmd
    - abstract.qmd
    - dedicatoria.qmd
    - agradecimientos.qmd
    - intro.qmd
    - preliminares.qmd
    - summary.qmd
    - references.qmd


bibliography: references.bib

format:
  html:
    theme:
      dark: darkly
      light: cerulean
    highlight-style: a11y
    html-math-method: mathjax
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem
    code-copy: true
  pdf:
    include-in-header:
       text: |
        \usepackage{amsfonts}
    lang: es
    documentclass: scrreport
    papersize: letter
    titlegraphic: FCFMLOGO.png
    institution: Universidad Autónoma de Chiapas
    email: jennifer.lopez67@unach.mx
    keep-tex: true
  epub:
    cover-image: FCFMLOGO.png
editor: visual
