{
  "hash": "beba9cfc744b1e22e9d3057a5eaf0271",
  "result": {
    "engine": "knitr",
    "markdown": "---\nlang: es\n---\n\n\n# Pronóstico de infectados diarios\n\n\n::: {.cell}\n\n:::\n\n\n## Obtención de datos\n\n::: {style=\"text-align: justify\"}\nConforme se ha referido previamente, se emplea el conjunto de datos global informado diariamente, disponible para su descarga en <https://covid19.who.int/WHO-COVID-19-global-data.csv.> Resulta relevante destacar que la base de datos consultada corresponde al 16 de Enero del 2023, restringiéndose a los datos concernientes exclusivamente a los casos confirmados en Irán entre el 20 de febrero y el 15 de agosto de 2020.\n\nEl análisis posterior se ha llevado a cabo empleando el software R versión 4.3.2. Con el propósito de realizar el análisis de los datos y la generación de gráficos, se procedió a convertir los datos al formato *ts*, lo que permitió su representación como una serie temporal.\n:::\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Se crea un objeto 'Date' diario\ninds <- seq(as.Date(\"2020-02-20\"), as.Date(\"2020-08-15\"), by = \"day\")\n# Se crea un objeto 'serie de tiempo' de frecuencia diaria\nConfirmed_ts <- ts(Confirmed_df[2], \n                   start = c(2020, as.numeric(format(inds[1], \"%j\"))),\n                   frequency = 365)\n```\n:::\n\n\n::: {.content-visible when-format=\"pdf\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![Serie de tiempo de los casos de COVID-19 confirmados en Irán del 20-02-2020 al 15-08-2020](confirmados_files/figure-html/fig-oripdf-1.png){#fig-oripdf width=672}\n:::\n:::\n\n:::\n\n::: {.content-visible when-format=\"html\"}\n::: {#fig-ori}\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item-overflow-hidden html-fill-item\" id=\"htmlwidget-82ead83e04b0e2847b97\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-82ead83e04b0e2847b97\">{\"x\":{\"visdat\":{\"b201c7435a1\":[\"function () \",\"plotlyVisDat\"]},\"cur_data\":\"b201c7435a1\",\"attrs\":{\"b201c7435a1\":{\"mode\":\"lines\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"scatter\"},\"b201c7435a1.1\":{\"mode\":\"lines\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"scatter\",\"x\":{},\"y\":{},\"inherit\":true}},\"layout\":{\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"showlegend\":false,\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"zerolinecolor\":\"#ffff\",\"zerolinewidth\":2,\"gridcolor\":\"ffff\",\"title\":\"Date\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"zerolinecolor\":\"#ffff\",\"zerolinewidth\":2,\"gridcolor\":\"ffff\",\"title\":\"Confirmed\"},\"plot_bgcolor\":\"#e5ecf6\",\"hovermode\":\"closest\"},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"data\":[{\"mode\":\"lines\",\"type\":\"scatter\",\"marker\":{\"color\":\"rgba(31,119,180,1)\",\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null},{\"mode\":\"lines\",\"type\":\"scatter\",\"x\":[\"2020-02-20\",\"2020-02-21\",\"2020-02-22\",\"2020-02-23\",\"2020-02-24\",\"2020-02-25\",\"2020-02-26\",\"2020-02-27\",\"2020-02-28\",\"2020-02-29\",\"2020-03-01\",\"2020-03-02\",\"2020-03-03\",\"2020-03-04\",\"2020-03-05\",\"2020-03-06\",\"2020-03-07\",\"2020-03-08\",\"2020-03-09\",\"2020-03-10\",\"2020-03-11\",\"2020-03-12\",\"2020-03-13\",\"2020-03-14\",\"2020-03-15\",\"2020-03-16\",\"2020-03-17\",\"2020-03-18\",\"2020-03-19\",\"2020-03-20\",\"2020-03-21\",\"2020-03-22\",\"2020-03-23\",\"2020-03-24\",\"2020-03-25\",\"2020-03-26\",\"2020-03-27\",\"2020-03-28\",\"2020-03-29\",\"2020-03-30\",\"2020-03-31\",\"2020-04-01\",\"2020-04-02\",\"2020-04-03\",\"2020-04-04\",\"2020-04-05\",\"2020-04-06\",\"2020-04-07\",\"2020-04-08\",\"2020-04-09\",\"2020-04-10\",\"2020-04-11\",\"2020-04-12\",\"2020-04-13\",\"2020-04-14\",\"2020-04-15\",\"2020-04-16\",\"2020-04-17\",\"2020-04-18\",\"2020-04-19\",\"2020-04-20\",\"2020-04-21\",\"2020-04-22\",\"2020-04-23\",\"2020-04-24\",\"2020-04-25\",\"2020-04-26\",\"2020-04-27\",\"2020-04-28\",\"2020-04-29\",\"2020-04-30\",\"2020-05-01\",\"2020-05-02\",\"2020-05-03\",\"2020-05-04\",\"2020-05-05\",\"2020-05-06\",\"2020-05-07\",\"2020-05-08\",\"2020-05-09\",\"2020-05-10\",\"2020-05-11\",\"2020-05-12\",\"2020-05-13\",\"2020-05-14\",\"2020-05-15\",\"2020-05-16\",\"2020-05-17\",\"2020-05-18\",\"2020-05-19\",\"2020-05-20\",\"2020-05-21\",\"2020-05-22\",\"2020-05-23\",\"2020-05-24\",\"2020-05-25\",\"2020-05-26\",\"2020-05-27\",\"2020-05-28\",\"2020-05-29\",\"2020-05-30\",\"2020-05-31\",\"2020-06-01\",\"2020-06-02\",\"2020-06-03\",\"2020-06-04\",\"2020-06-05\",\"2020-06-06\",\"2020-06-07\",\"2020-06-08\",\"2020-06-09\",\"2020-06-10\",\"2020-06-11\",\"2020-06-12\",\"2020-06-13\",\"2020-06-14\",\"2020-06-15\",\"2020-06-16\",\"2020-06-17\",\"2020-06-18\",\"2020-06-19\",\"2020-06-20\",\"2020-06-21\",\"2020-06-22\",\"2020-06-23\",\"2020-06-24\",\"2020-06-25\",\"2020-06-26\",\"2020-06-27\",\"2020-06-28\",\"2020-06-29\",\"2020-06-30\",\"2020-07-01\",\"2020-07-02\",\"2020-07-03\",\"2020-07-04\",\"2020-07-05\",\"2020-07-06\",\"2020-07-07\",\"2020-07-08\",\"2020-07-09\",\"2020-07-10\",\"2020-07-11\",\"2020-07-12\",\"2020-07-13\",\"2020-07-14\",\"2020-07-15\",\"2020-07-16\",\"2020-07-17\",\"2020-07-18\",\"2020-07-19\",\"2020-07-20\",\"2020-07-21\",\"2020-07-22\",\"2020-07-23\",\"2020-07-24\",\"2020-07-25\",\"2020-07-26\",\"2020-07-27\",\"2020-07-28\",\"2020-07-29\",\"2020-07-30\",\"2020-07-31\",\"2020-08-01\",\"2020-08-02\",\"2020-08-03\",\"2020-08-04\",\"2020-08-05\",\"2020-08-06\",\"2020-08-07\",\"2020-08-08\",\"2020-08-09\",\"2020-08-10\",\"2020-08-11\",\"2020-08-12\",\"2020-08-13\",\"2020-08-14\",\"2020-08-15\"],\"y\":[3,13,10,15,4,48,44,0,249,0,205,0,908,1421,591,1234,1076,743,595,881,958,1075,1289,1365,1254,1008,1178,1192,1046,1233,966,1028,1411,1762,2206,2389,2926,3076,2901,3186,3111,2987,2875,2715,2560,0,2483,2274,2089,1997,1634,1972,1837,1657,1617,1574,1512,1606,1499,1374,1343,1294,1297,1194,1030,1168,1134,1153,991,1112,1073,983,1006,802,976,1223,1323,1680,1485,1556,1529,1383,1683,1481,1958,1808,2102,1757,1806,2294,2111,2346,2392,2311,1869,2180,2023,1787,2080,2258,2819,2282,2516,2979,3117,3134,3574,2886,2269,2364,2043,2095,2011,2238,2369,2410,2472,2449,2563,2612,2596,2615,2322,2368,2573,2445,2531,2595,2628,2456,2489,2536,2457,2549,2652,2566,2449,2560,2613,2637,2691,2079,2262,2397,2186,2349,2521,2388,2500,2379,2166,2182,2414,2625,2586,2621,2489,2316,2333,2434,2667,2636,2621,2674,2548,2685,2598,2751,2697,2634,2450,2125,2020,2132,2345,2510,2625,2501],\"marker\":{\"color\":\"rgba(255,127,14,1)\",\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\nSerie de tiempo de los casos de COVID-19 confirmados en Irán del 20-02-2020 al 15-08-2020\n:::\n:::\n\n::: {.content-visible when-format=\"pdf\"}\n::: {style=\"text-align: justify\"}\nLa gráfica de la @fig-oripdf exhibe la serie temporal derivada de la base de datos, en la cual se evidencia la ausencia de información para los días 27 y 29 de Febrero, así como para el 02 de Marzo y el 05 de Abril de 2020. Para subsanar esta carencia de datos, se llevó a cabo una interpolación promedio a fin de sustituir los valores faltantes. La @fig-tspdf muestra la serie de tiempo resultante de estas correcciones.\n:::\n:::\n\n::: {.content-visible when-format=\"html\" style=\"text-align: justify\"}\nLa gráfica de la @fig-ori exhibe la serie temporal derivada de la base de datos, en la cual se evidencia la ausencia de información para los días 27 y 29 de Febrero, así como para el 02 de Marzo y el 05 de Abril de 2020. Para subsanar esta carencia de datos, se llevó a cabo una interpolación promedio a fin de sustituir los valores faltantes. La @tbl-datatable muestra la base de datos con las modificaciones efectuadas, así como la serie de tiempo (@fig-ts) resultante de estas correcciones.\n:::\n\n\n::: {.cell}\n\n:::\n\n\n::: {.content-visible when-format=\"html\"}\n\n::: {#tbl-datatable .cell tbl-cap='Casos confirmados ajustados del 20-02-2020 al 15-08-2020'}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item-overflow-hidden html-fill-item\" id=\"htmlwidget-0d7bbec0a28d2164776e\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-0d7bbec0a28d2164776e\">{\"x\":{\"style\":\"bootstrap4\",\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\",\"27\",\"28\",\"29\",\"30\",\"31\",\"32\",\"33\",\"34\",\"35\",\"36\",\"37\",\"38\",\"39\",\"40\",\"41\",\"42\",\"43\",\"44\",\"45\",\"46\",\"47\",\"48\",\"49\",\"50\",\"51\",\"52\",\"53\",\"54\",\"55\",\"56\",\"57\",\"58\",\"59\",\"60\",\"61\",\"62\",\"63\",\"64\",\"65\",\"66\",\"67\",\"68\",\"69\",\"70\",\"71\",\"72\",\"73\",\"74\",\"75\",\"76\",\"77\",\"78\",\"79\",\"80\",\"81\",\"82\",\"83\",\"84\",\"85\",\"86\",\"87\",\"88\",\"89\",\"90\",\"91\",\"92\",\"93\",\"94\",\"95\",\"96\",\"97\",\"98\",\"99\",\"100\",\"101\",\"102\",\"103\",\"104\",\"105\",\"106\",\"107\",\"108\",\"109\",\"110\",\"111\",\"112\",\"113\",\"114\",\"115\",\"116\",\"117\",\"118\",\"119\",\"120\",\"121\",\"122\",\"123\",\"124\",\"125\",\"126\",\"127\",\"128\",\"129\",\"130\",\"131\",\"132\",\"133\",\"134\",\"135\",\"136\",\"137\",\"138\",\"139\",\"140\",\"141\",\"142\",\"143\",\"144\",\"145\",\"146\",\"147\",\"148\",\"149\",\"150\",\"151\",\"152\",\"153\",\"154\",\"155\",\"156\",\"157\",\"158\",\"159\",\"160\",\"161\",\"162\",\"163\",\"164\",\"165\",\"166\",\"167\",\"168\",\"169\",\"170\",\"171\",\"172\",\"173\",\"174\",\"175\",\"176\",\"177\",\"178\"],[\"2020-02-20\",\"2020-02-21\",\"2020-02-22\",\"2020-02-23\",\"2020-02-24\",\"2020-02-25\",\"2020-02-26\",\"2020-02-27\",\"2020-02-28\",\"2020-02-29\",\"2020-03-01\",\"2020-03-02\",\"2020-03-03\",\"2020-03-04\",\"2020-03-05\",\"2020-03-06\",\"2020-03-07\",\"2020-03-08\",\"2020-03-09\",\"2020-03-10\",\"2020-03-11\",\"2020-03-12\",\"2020-03-13\",\"2020-03-14\",\"2020-03-15\",\"2020-03-16\",\"2020-03-17\",\"2020-03-18\",\"2020-03-19\",\"2020-03-20\",\"2020-03-21\",\"2020-03-22\",\"2020-03-23\",\"2020-03-24\",\"2020-03-25\",\"2020-03-26\",\"2020-03-27\",\"2020-03-28\",\"2020-03-29\",\"2020-03-30\",\"2020-03-31\",\"2020-04-01\",\"2020-04-02\",\"2020-04-03\",\"2020-04-04\",\"2020-04-05\",\"2020-04-06\",\"2020-04-07\",\"2020-04-08\",\"2020-04-09\",\"2020-04-10\",\"2020-04-11\",\"2020-04-12\",\"2020-04-13\",\"2020-04-14\",\"2020-04-15\",\"2020-04-16\",\"2020-04-17\",\"2020-04-18\",\"2020-04-19\",\"2020-04-20\",\"2020-04-21\",\"2020-04-22\",\"2020-04-23\",\"2020-04-24\",\"2020-04-25\",\"2020-04-26\",\"2020-04-27\",\"2020-04-28\",\"2020-04-29\",\"2020-04-30\",\"2020-05-01\",\"2020-05-02\",\"2020-05-03\",\"2020-05-04\",\"2020-05-05\",\"2020-05-06\",\"2020-05-07\",\"2020-05-08\",\"2020-05-09\",\"2020-05-10\",\"2020-05-11\",\"2020-05-12\",\"2020-05-13\",\"2020-05-14\",\"2020-05-15\",\"2020-05-16\",\"2020-05-17\",\"2020-05-18\",\"2020-05-19\",\"2020-05-20\",\"2020-05-21\",\"2020-05-22\",\"2020-05-23\",\"2020-05-24\",\"2020-05-25\",\"2020-05-26\",\"2020-05-27\",\"2020-05-28\",\"2020-05-29\",\"2020-05-30\",\"2020-05-31\",\"2020-06-01\",\"2020-06-02\",\"2020-06-03\",\"2020-06-04\",\"2020-06-05\",\"2020-06-06\",\"2020-06-07\",\"2020-06-08\",\"2020-06-09\",\"2020-06-10\",\"2020-06-11\",\"2020-06-12\",\"2020-06-13\",\"2020-06-14\",\"2020-06-15\",\"2020-06-16\",\"2020-06-17\",\"2020-06-18\",\"2020-06-19\",\"2020-06-20\",\"2020-06-21\",\"2020-06-22\",\"2020-06-23\",\"2020-06-24\",\"2020-06-25\",\"2020-06-26\",\"2020-06-27\",\"2020-06-28\",\"2020-06-29\",\"2020-06-30\",\"2020-07-01\",\"2020-07-02\",\"2020-07-03\",\"2020-07-04\",\"2020-07-05\",\"2020-07-06\",\"2020-07-07\",\"2020-07-08\",\"2020-07-09\",\"2020-07-10\",\"2020-07-11\",\"2020-07-12\",\"2020-07-13\",\"2020-07-14\",\"2020-07-15\",\"2020-07-16\",\"2020-07-17\",\"2020-07-18\",\"2020-07-19\",\"2020-07-20\",\"2020-07-21\",\"2020-07-22\",\"2020-07-23\",\"2020-07-24\",\"2020-07-25\",\"2020-07-26\",\"2020-07-27\",\"2020-07-28\",\"2020-07-29\",\"2020-07-30\",\"2020-07-31\",\"2020-08-01\",\"2020-08-02\",\"2020-08-03\",\"2020-08-04\",\"2020-08-05\",\"2020-08-06\",\"2020-08-07\",\"2020-08-08\",\"2020-08-09\",\"2020-08-10\",\"2020-08-11\",\"2020-08-12\",\"2020-08-13\",\"2020-08-14\",\"2020-08-15\"],[3,13,10,15,4,48,44,146.5,249,227,205,556.5,908,1421,591,1234,1076,743,595,881,958,1075,1289,1365,1254,1008,1178,1192,1046,1233,966,1028,1411,1762,2206,2389,2926,3076,2901,3186,3111,2987,2875,2715,2560,2521.5,2483,2274,2089,1997,1634,1972,1837,1657,1617,1574,1512,1606,1499,1374,1343,1294,1297,1194,1030,1168,1134,1153,991,1112,1073,983,1006,802,976,1223,1323,1680,1485,1556,1529,1383,1683,1481,1958,1808,2102,1757,1806,2294,2111,2346,2392,2311,1869,2180,2023,1787,2080,2258,2819,2282,2516,2979,3117,3134,3574,2886,2269,2364,2043,2095,2011,2238,2369,2410,2472,2449,2563,2612,2596,2615,2322,2368,2573,2445,2531,2595,2628,2456,2489,2536,2457,2549,2652,2566,2449,2560,2613,2637,2691,2079,2262,2397,2186,2349,2521,2388,2500,2379,2166,2182,2414,2625,2586,2621,2489,2316,2333,2434,2667,2636,2621,2674,2548,2685,2598,2751,2697,2634,2450,2125,2020,2132,2345,2510,2625,2501]],\"container\":\"<table class=\\\"table table-striped table-hover row-border order-column display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>Date<\\/th>\\n      <th>Confirmed<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":2},{\"orderable\":false,\"targets\":0}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n:::\n\n::: {.content-visible when-format=\"html\"}\n::: {#fig-ts}\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item-overflow-hidden html-fill-item\" id=\"htmlwidget-504aaa0a6827c59fd832\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-504aaa0a6827c59fd832\">{\"x\":{\"visdat\":{\"b2061b26d57\":[\"function () \",\"plotlyVisDat\"]},\"cur_data\":\"b2061b26d57\",\"attrs\":{\"b2061b26d57\":{\"mode\":\"lines\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"scatter\"},\"b2061b26d57.1\":{\"mode\":\"lines\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"scatter\",\"x\":{},\"y\":{},\"inherit\":true}},\"layout\":{\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"showlegend\":false,\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"zerolinecolor\":\"#ffff\",\"zerolinewidth\":2,\"gridcolor\":\"ffff\",\"title\":\"Date\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"zerolinecolor\":\"#ffff\",\"zerolinewidth\":2,\"gridcolor\":\"ffff\",\"title\":\"Confirmed\"},\"plot_bgcolor\":\"#e5ecf6\",\"hovermode\":\"closest\"},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"data\":[{\"mode\":\"lines\",\"type\":\"scatter\",\"marker\":{\"color\":\"rgba(31,119,180,1)\",\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null},{\"mode\":\"lines\",\"type\":\"scatter\",\"x\":[\"2020-02-20\",\"2020-02-21\",\"2020-02-22\",\"2020-02-23\",\"2020-02-24\",\"2020-02-25\",\"2020-02-26\",\"2020-02-27\",\"2020-02-28\",\"2020-02-29\",\"2020-03-01\",\"2020-03-02\",\"2020-03-03\",\"2020-03-04\",\"2020-03-05\",\"2020-03-06\",\"2020-03-07\",\"2020-03-08\",\"2020-03-09\",\"2020-03-10\",\"2020-03-11\",\"2020-03-12\",\"2020-03-13\",\"2020-03-14\",\"2020-03-15\",\"2020-03-16\",\"2020-03-17\",\"2020-03-18\",\"2020-03-19\",\"2020-03-20\",\"2020-03-21\",\"2020-03-22\",\"2020-03-23\",\"2020-03-24\",\"2020-03-25\",\"2020-03-26\",\"2020-03-27\",\"2020-03-28\",\"2020-03-29\",\"2020-03-30\",\"2020-03-31\",\"2020-04-01\",\"2020-04-02\",\"2020-04-03\",\"2020-04-04\",\"2020-04-05\",\"2020-04-06\",\"2020-04-07\",\"2020-04-08\",\"2020-04-09\",\"2020-04-10\",\"2020-04-11\",\"2020-04-12\",\"2020-04-13\",\"2020-04-14\",\"2020-04-15\",\"2020-04-16\",\"2020-04-17\",\"2020-04-18\",\"2020-04-19\",\"2020-04-20\",\"2020-04-21\",\"2020-04-22\",\"2020-04-23\",\"2020-04-24\",\"2020-04-25\",\"2020-04-26\",\"2020-04-27\",\"2020-04-28\",\"2020-04-29\",\"2020-04-30\",\"2020-05-01\",\"2020-05-02\",\"2020-05-03\",\"2020-05-04\",\"2020-05-05\",\"2020-05-06\",\"2020-05-07\",\"2020-05-08\",\"2020-05-09\",\"2020-05-10\",\"2020-05-11\",\"2020-05-12\",\"2020-05-13\",\"2020-05-14\",\"2020-05-15\",\"2020-05-16\",\"2020-05-17\",\"2020-05-18\",\"2020-05-19\",\"2020-05-20\",\"2020-05-21\",\"2020-05-22\",\"2020-05-23\",\"2020-05-24\",\"2020-05-25\",\"2020-05-26\",\"2020-05-27\",\"2020-05-28\",\"2020-05-29\",\"2020-05-30\",\"2020-05-31\",\"2020-06-01\",\"2020-06-02\",\"2020-06-03\",\"2020-06-04\",\"2020-06-05\",\"2020-06-06\",\"2020-06-07\",\"2020-06-08\",\"2020-06-09\",\"2020-06-10\",\"2020-06-11\",\"2020-06-12\",\"2020-06-13\",\"2020-06-14\",\"2020-06-15\",\"2020-06-16\",\"2020-06-17\",\"2020-06-18\",\"2020-06-19\",\"2020-06-20\",\"2020-06-21\",\"2020-06-22\",\"2020-06-23\",\"2020-06-24\",\"2020-06-25\",\"2020-06-26\",\"2020-06-27\",\"2020-06-28\",\"2020-06-29\",\"2020-06-30\",\"2020-07-01\",\"2020-07-02\",\"2020-07-03\",\"2020-07-04\",\"2020-07-05\",\"2020-07-06\",\"2020-07-07\",\"2020-07-08\",\"2020-07-09\",\"2020-07-10\",\"2020-07-11\",\"2020-07-12\",\"2020-07-13\",\"2020-07-14\",\"2020-07-15\",\"2020-07-16\",\"2020-07-17\",\"2020-07-18\",\"2020-07-19\",\"2020-07-20\",\"2020-07-21\",\"2020-07-22\",\"2020-07-23\",\"2020-07-24\",\"2020-07-25\",\"2020-07-26\",\"2020-07-27\",\"2020-07-28\",\"2020-07-29\",\"2020-07-30\",\"2020-07-31\",\"2020-08-01\",\"2020-08-02\",\"2020-08-03\",\"2020-08-04\",\"2020-08-05\",\"2020-08-06\",\"2020-08-07\",\"2020-08-08\",\"2020-08-09\",\"2020-08-10\",\"2020-08-11\",\"2020-08-12\",\"2020-08-13\",\"2020-08-14\",\"2020-08-15\"],\"y\":[3,13,10,15,4,48,44,146.5,249,227,205,556.5,908,1421,591,1234,1076,743,595,881,958,1075,1289,1365,1254,1008,1178,1192,1046,1233,966,1028,1411,1762,2206,2389,2926,3076,2901,3186,3111,2987,2875,2715,2560,2521.5,2483,2274,2089,1997,1634,1972,1837,1657,1617,1574,1512,1606,1499,1374,1343,1294,1297,1194,1030,1168,1134,1153,991,1112,1073,983,1006,802,976,1223,1323,1680,1485,1556,1529,1383,1683,1481,1958,1808,2102,1757,1806,2294,2111,2346,2392,2311,1869,2180,2023,1787,2080,2258,2819,2282,2516,2979,3117,3134,3574,2886,2269,2364,2043,2095,2011,2238,2369,2410,2472,2449,2563,2612,2596,2615,2322,2368,2573,2445,2531,2595,2628,2456,2489,2536,2457,2549,2652,2566,2449,2560,2613,2637,2691,2079,2262,2397,2186,2349,2521,2388,2500,2379,2166,2182,2414,2625,2586,2621,2489,2316,2333,2434,2667,2636,2621,2674,2548,2685,2598,2751,2697,2634,2450,2125,2020,2132,2345,2510,2625,2501],\"marker\":{\"color\":\"rgba(255,127,14,1)\",\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\nSerie de tiempo de los casos de COVID-19 confirmados en Irán del 20-02-2020 al 15-08-2020\n:::\n:::\n\n::: {.content-visible when-format=\"pdf\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![Serie de tiempo de los casos de COVID-19 confirmados en Irán del 20-02-2020 al 15-08-2020](confirmados_files/figure-html/fig-tspdf-1.png){#fig-tspdf width=672}\n:::\n:::\n\n:::\n\n## Análisis de la serie de tiempo de casos confirmados de COVID-19 en Irán\n\n### Estadística descriptiva\n\n::: {style=\"text-align: justify\"}\nCon el propósito de llevar a cabo una auditoría de los datos y al mismo tiempo una descripción preliminar, se ejecuta un estudio de estadística descriptiva que arroja los resultados correspondientes, incluyendo un gráfico Boxplot (@fig-box) para representar la información o\n:::\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n      3    1304    2181    1923    2529    3574 \n```\n\n\n:::\n:::\n\n\n::: {#fig-box}\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item-overflow-hidden html-fill-item\" id=\"htmlwidget-e6975628badb818d48c7\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-e6975628badb818d48c7\">{\"x\":{\"visdat\":{\"b205f32297d\":[\"function () \",\"plotlyVisDat\"]},\"cur_data\":\"b205f32297d\",\"attrs\":{\"b205f32297d\":{\"y\":{},\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"box\"}},\"layout\":{\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"title\":\"Confirmed\"},\"xaxis\":{\"domain\":[0,1],\"automargin\":true},\"hovermode\":\"closest\",\"showlegend\":false},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"data\":[{\"fillcolor\":\"rgba(31,119,180,0.5)\",\"y\":[3,13,10,15,4,48,44,146.5,249,227,205,556.5,908,1421,591,1234,1076,743,595,881,958,1075,1289,1365,1254,1008,1178,1192,1046,1233,966,1028,1411,1762,2206,2389,2926,3076,2901,3186,3111,2987,2875,2715,2560,2521.5,2483,2274,2089,1997,1634,1972,1837,1657,1617,1574,1512,1606,1499,1374,1343,1294,1297,1194,1030,1168,1134,1153,991,1112,1073,983,1006,802,976,1223,1323,1680,1485,1556,1529,1383,1683,1481,1958,1808,2102,1757,1806,2294,2111,2346,2392,2311,1869,2180,2023,1787,2080,2258,2819,2282,2516,2979,3117,3134,3574,2886,2269,2364,2043,2095,2011,2238,2369,2410,2472,2449,2563,2612,2596,2615,2322,2368,2573,2445,2531,2595,2628,2456,2489,2536,2457,2549,2652,2566,2449,2560,2613,2637,2691,2079,2262,2397,2186,2349,2521,2388,2500,2379,2166,2182,2414,2625,2586,2621,2489,2316,2333,2434,2667,2636,2621,2674,2548,2685,2598,2751,2697,2634,2450,2125,2020,2132,2345,2510,2625,2501],\"type\":\"box\",\"marker\":{\"color\":\"rgba(31,119,180,1)\",\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\nBoxplot de casos confirmados de COVID-19 en Irán del 20-02-2020 al 15-08-2020\n:::\n\n### Componentes de la serie de tiempo\n\n::: {style=\"text-align: justify\"}\nLos componentes identificados en la serie de tiempo de casos confirmados de COVID-19 en Irán, revelan distintos patrones y características.\n\nEn primer lugar, se observa una tendencia discernible en el gráfico de la serie temporal (@fig-ts). Por ejemplo, entre el 30 de marzo y el 03 de mayo de 2020, se evidencia una tendencia negativa o decreciente, seguida por una tendencia creciente a partir del 03 de mayo en adelante. Estos cambios en la tendencia podrían indicar fluctuaciones significativas en la evolución de los casos confirmados durante esos periodos específicos.\n\nEn cuanto a la estacionalidad, aunque no se identifica claramente a simple vista en el periodo observado, la extensión del análisis a un periodo más amplio podría revelar patrones recurrentes o ciclos temporales característicos. Es posible que ciertos patrones estacionales se manifiesten en intervalos más extensos de la serie temporal, lo que implicaría variaciones sistemáticas y repetitivas en los datos en períodos específicos.\n\nPor último, se destacan pequeñas subidas y bajadas en el gráfico que sugieren la presencia de **ruido** en la serie temporal. Estas fluctuaciones irregulares podrían atribuirse a diversas causas, como posibles errores en la recolección de datos o fluctuaciones aleatorias inherentes al comportamiento de la enfermedad. Es importante considerar estas variaciones no sistemáticas al analizar la serie temporal, ya que podrían influir en la interpretación de los patrones y tendencias observadas.\n:::\n\n### Estacionariedad\n\n::: {style=\"text-align: justify\"}\nA continuación, se emplea el test de Dickey-Fuller para examinar la presencia de estacionariedad en la serie temporal. Este test fue utilizado con la finalidad de identificar la existencia de raíces unitarias en la serie, lo cual permite inferir la presencia o ausencia de estacionariedad en los datos analizados.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadf.test(Confirmed_ts, alternative = \"stationary\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAugmented Dickey-Fuller Test\n\ndata:  Confirmed_ts\nDickey-Fuller = -2.9529, Lag order = 5, p-value = 0.1781\nalternative hypothesis: stationary\n```\n\n\n:::\n:::\n\n\n::: {style=\"text-align: justify\"}\nLa hipótesis nula $(H_0)$ asume la presencia de raíces unitarias, lo que indica no estacionariedad en la serie. Al obtener un $p-$valor superior al nivel de significancia establecido el cuál es del $95\\%$, no se rechaza la hipótesis nula, sugiriendo la ausencia de estacionariedad en la serie de tiempo de casos confirmados.\n\nAdemás, se complementa la evaluación de la estacionalidad mediante la inspección de los gráficos de la función de autocorrelación (ACF) y la función de autocorrelación parcial (PACF). Estos gráficos se utilizan para identificar patrones de autocorrelación en la serie temporal, lo que permite visualizar la presencia de estacionalidad, tendencias o ciclos.\n:::\n\n::: {style=\"text-align: justify\"}\nLa serie de tiempo representada en la @fig-ts exhibe un comportamiento característico de deambulación aleatoria. Dado que el valor de la variable $X_{t+1}$ generalmente se encuentra en proximidad al valor $X_t$, se evidencia una autocorrelación positiva notablemente marcada entre las variables $X_t$ y $X_{t+1}$.\n\n::: {#fig-acf}\n\n::: {.cell}\n\n```{.r .cell-code}\nautoplot(acf(Confirmed_ts, plot = FALSE), \n         main=\"Autocorrelograma de casos confirmados\")\n```\n\n::: {.cell-output-display}\n![](confirmados_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nAutocorrelograma de los casos confirmados de COVID-19 en Irán\n:::\n\nEn la @fig-acf se observa que la autocorrelación (vea @eq-autocorr) entre $X_t$ y $X_{t+k}$ decrece con el incremento del retraso $k$. Este declive conduce a la constatación de que, a un desfase de $20$, existe una correlación bastante débil entre $X_t$ y $X_{t+20}$. Al analizar el gráfico de la función de autocorrelación (ACF), se aprecia que $\\rho_{20}\\approx 0.19$.\n\nLa gráfica de la Función de Autocorrelación Parcial (PACF) proporciona información valiosa sobre la estructura de autocorrelación de una serie temporal una vez han sido eliminadas las correlaciones debidas a los intervalos de tiempo intermedios.\n\n::: {#fig-pacf}\n\n::: {.cell}\n\n```{.r .cell-code}\nggPacf((Confirmed_ts), main = 'Autocorrelograma parcial de casos confirmados')\n```\n\n::: {.cell-output-display}\n![](confirmados_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nAutocorrelograma Parcial de los casos confirmados de COVID-19 en Irán\n:::\n\nConsiderando que los datos se ajustan a un modelo de series de tiempo, la @fig-pacf indica que el valor de correlación $\\phi_{15}$ es ligeramente superior a $0.25$, aproximadamente $\\phi_{52}\\approx 0.16$, y $\\phi_{76}\\approx 0.15$, mientras que para los restantes valores, la correlación parcial no es nula.\n\n::: remark\nDe acuerdo con la gráfica de la Función de Autocorrelación Parcial @fig-pacf, se observa un corte abrupto después del rezago 4, lo cual sugiere que las autocorrelaciones parciales más allá de ese punto no poseen significancia estadística. Por consiguiente, se infiere la posibilidad de ajustar un modelo autoregresivo AR(4) a la base de datos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tswge)\ncoeff <- est.ar.wge(Confirmed_ts, p=4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  \n  \nCoefficients of AR polynomial:  \n0.8656 0.1724 0.0592 -0.1318 \n\n                           AR Factor Table \nFactor                 Roots                Abs Recip    System Freq \n1-0.9605B              1.0411               0.9605       0.0000\n1-0.5355B              1.8675               0.5355       0.0000\n1+0.6303B+0.2563B^2   -1.2298+-1.5459i      0.5062       0.3570\n  \n  \n```\n\n\n:::\n\n```{.r .cell-code}\ncoeff$phi #coeficientes\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  0.86563811  0.17237111  0.05917558 -0.13180534\n```\n\n\n:::\n\n```{.r .cell-code}\ncoeff$xbar #media\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1922.868\n```\n\n\n:::\n\n```{.r .cell-code}\ncoeff$avar #varianza finita\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 47818.04\n```\n\n\n:::\n:::\n\n\nEl modelo autoregresivo AR(4) se expresa mediante la siguiente ecuación:\n\n$$\n(1-0.865B-0.172B^2-0.059B^3+0.131B^4)(X_t-1922.868)+a_t\n$$ {#eq-AR4}\n\ndonde $\\hat{\\sigma}_a^2 = 47818.04$.\n:::\n:::\n\n::: {style=\"text-align: justify\"}\nEl análisis del ACF y PACF proporcionó información sobre la relación de los puntos de datos con sus rezagos, permitiendo observar posibles patrones estacionales. La presencia de picos significativos en estos gráficos podría indicar la existencia de estacionalidad en la serie de tiempo.\n:::\n\n## Entrenamiento, modelado, pronóstico y métricas de rendimiento\n\n::: {style=\"text-align: justify\"}\nSe procede a la evaluación del rendimiento de métodos destinados al ajuste y consecuente pronóstico. Específicamente, se contempla el método de suavizamiento exponencial de Holt-Winters y el ajuste mediante un modelo de red neuronal del tipo perceptrón multicapa. Ambos procedimientos requieren la subdivisión de los datos en conjuntos destinados a entrenamiento y prueba. El set inicial, compuesto por el $70\\%$ de los datos, se emplea para el entrenamiento de los modelos, mientras que el $30\\%$ restante se reservará para llevar a cabo las pruebas pertinentes.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nConfirmed_ts <- ts(Confirmed_ts,frequency=1)\ntsize <- round(0.7 * nrow(Confirmed_df))\ntrain_confirmed <- window(Confirmed_ts,end=tsize)\ntest_confirmed <- window(Confirmed_ts,start=tsize+1)\n```\n:::\n\n\n### Holt-Winters {#sec-holt-winters}\n\n::: {style=\"text-align: justify\"}\nCon el fin de determinar la descomposición más adecuada para los datos en cuestión, se empleó un criterio elaborado basado en el coeficiente de variación, el cual proporciona una recomendación entre las dos versiones disponibles.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nDescRec <- function(x){\n  n = length(x)\n  di = rep(0, n-1)\n  ci = rep(0, n-1)\n  for (i in 1:n-1) {\n    di[i] = x[i+1] - x[i]\n    ci[i] = x[i+1] / x[i]\n  }\n  d <- cv(di) \n  c <- cv(ci) / mean(di)\n  if(d < c)\n    print(\"Se recomienda la descomposición aditiva\")\n  else\n    print(\"Se recomienda la descomposición multiplicativa\")\n}\nDescRec(train_confirmed)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Se recomienda la descomposición multiplicativa\"\n```\n\n\n:::\n:::\n\n\nDe acuerdo con la recomendación observada, se sugiere la utilización de la versión multiplicativa (vea @eq-muldecom). En consecuencia, se procede a mostrar la representación gráfica de la descomposición multiplicativa de la serie temporal.\n\n::: {#fig-descomp}\n\n::: {.cell}\n\n```{.r .cell-code}\nts_train <- ts(train_confirmed, frequency = 2)\ncomponents_ts <- decompose(ts_train, type = 'mult')\nplot(components_ts)\n```\n\n::: {.cell-output-display}\n![](confirmados_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\nDescomposición multiplicativa de la serie de tiempo\n:::\n\nSe procede ahora a la aplicación del modelo multiplicativo de Holt-Winters a la serie temporal de los datos de entrenamiento utilizando una frecuencia de dos, con el fin de permitir la aplicabilidad del modelo.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHWc <- HoltWinters(ts_train, seasonal = 'mult')\nHWc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nHolt-Winters exponential smoothing with trend and multiplicative seasonal component.\n\nCall:\nHoltWinters(x = ts_train, seasonal = \"mult\")\n\nSmoothing parameters:\n alpha: 0.729859\n beta : 0\n gamma: 0.6494094\n\nCoefficients:\n          [,1]\na  2289.283568\nb     2.250000\ns1    1.119185\ns2    1.113547\n```\n\n\n:::\n:::\n\n\n::: {style=\"text-align: justify\"}\nFinalmente, utilizando el modelo de entrenamiento desarrollado en la fase previa, se lleva a cabo la proyección con un horizonte de predicción igual en extensión a los datos de prueba, acompañado de un intervalo de confianza que oscila entre el $80\\%$ y el $95\\%$.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHWc_for <- forecast(HWc, h=length(test_confirmed))\n```\n:::\n\n\n::: {.callout-note style=\"text-align: justify\"}\nLas funciones aplicadas en esta sección son parte de la librería ***stats*** @stats de R.\n:::\n\n### MLP\n\n::: {style=\"text-align: justify\"}\nPosteriormente, se procede al entrenamiento del modelo MLP (Perceptrón Multicapa). La cantidad de capas ocultas y la configuración de nodos en cada capa se determinaron de manera automatizada mediante el método de [validación cruzada de 5 pliegues](redes.qmd#sec-validación-cruzada-de-k-pliegues). Asimismo, se eligió la función de activación como sigmoide, y el proceso de entrenamiento del modelo se ejecutó a lo largo de 20 iteraciones.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfitc <- mlp(train_confirmed, hd.auto.type=\"cv\", reps=20, comb='median')\nfitc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMLP fit with 1 hidden node and 20 repetitions.\nUnivariate lags: (1,2,4)\nForecast combined using the median operator.\nMSE: 57290.4484.\n```\n\n\n:::\n:::\n\n\n::: {#fig-red}\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(fitc)\n```\n\n::: {.cell-output-display}\n![](confirmados_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\nEstructura de la red neuronal resultante\n:::\n\n::: {style=\"text-align: justify\"}\nPara llevar a cabo el pronóstico, se emplea el modelo de entrenamiento creado en la etapa anterior, manteniendo un horizonte de predicción que coincide en duración con los datos de prueba, tal como se hizo con la técnica anterior.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfrcc <- forecast(fitc,h=length(test_confirmed))\n```\n:::\n\n\n::: {.callout-note style=\"text-align: justify\"}\nLas funciones aplicadas en esta sección son parte de la librería ***nnfor*** @nnfor de R.\n:::\n\n### Comparación de pronósticos con el conjunto de datos de prueba\n\n::: {style=\"text-align: justify\"}\nCon el propósito de llevar a cabo un análisis cuantitativo exhaustivo, se presenta a continuación una tabla comparativa de los resultados derivados de las dos técnicas implementadas y la base de datos de prueba. Posteriormente, se exhiben gráficas representativas de estos resultados. En la @fig-phw se muestra el pronóstico mediante Holt-Winters acompañado de su respectivo intervalo de confianza. En contraste, en la @fig-pmlp, la gráfica punteada en color rojo representa el comportamiento real de los datos, mientras que en azul se representa el pronóstico obtenido a través de la red MLP.\n:::\n\n::: {.content-visible when-format=\"html\"}\n\n::: {#tbl-forecast .cell tbl-cap='Comparación de Resultados entre las técnicas y los datos reales para evaluar precisión'}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item-overflow-hidden html-fill-item\" id=\"htmlwidget-9827cf6bc9da91f06236\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-9827cf6bc9da91f06236\">{\"x\":{\"style\":\"bootstrap4\",\"filter\":\"none\",\"vertical\":false,\"data\":[[\"t+1\",\"t+2\",\"t+3\",\"t+4\",\"t+5\",\"t+6\",\"t+7\",\"t+8\",\"t+9\",\"t+10\",\"t+11\",\"t+12\",\"t+13\",\"t+14\",\"t+15\",\"t+16\",\"t+17\",\"t+18\",\"t+19\",\"t+20\",\"t+21\",\"t+22\",\"t+23\",\"t+24\",\"t+25\",\"t+26\",\"t+27\",\"t+28\",\"t+29\",\"t+30\",\"t+31\",\"t+32\",\"t+33\",\"t+34\",\"t+35\",\"t+36\",\"t+37\",\"t+38\",\"t+39\",\"t+40\",\"t+41\",\"t+42\",\"t+43\",\"t+44\",\"t+45\",\"t+46\",\"t+47\",\"t+48\",\"t+49\",\"t+50\",\"t+51\",\"t+52\",\"t+53\"],[\"2020-06-24\",\"2020-06-25\",\"2020-06-26\",\"2020-06-27\",\"2020-06-28\",\"2020-06-29\",\"2020-06-30\",\"2020-07-01\",\"2020-07-02\",\"2020-07-03\",\"2020-07-04\",\"2020-07-05\",\"2020-07-06\",\"2020-07-07\",\"2020-07-08\",\"2020-07-09\",\"2020-07-10\",\"2020-07-11\",\"2020-07-12\",\"2020-07-13\",\"2020-07-14\",\"2020-07-15\",\"2020-07-16\",\"2020-07-17\",\"2020-07-18\",\"2020-07-19\",\"2020-07-20\",\"2020-07-21\",\"2020-07-22\",\"2020-07-23\",\"2020-07-24\",\"2020-07-25\",\"2020-07-26\",\"2020-07-27\",\"2020-07-28\",\"2020-07-29\",\"2020-07-30\",\"2020-07-31\",\"2020-08-01\",\"2020-08-02\",\"2020-08-03\",\"2020-08-04\",\"2020-08-05\",\"2020-08-06\",\"2020-08-07\",\"2020-08-08\",\"2020-08-09\",\"2020-08-10\",\"2020-08-11\",\"2020-08-12\",\"2020-08-13\",\"2020-08-14\",\"2020-08-15\"],[2445,2531,2595,2628,2456,2489,2536,2457,2549,2652,2566,2449,2560,2613,2637,2691,2079,2262,2397,2186,2349,2521,2388,2500,2379,2166,2182,2414,2625,2586,2621,2489,2316,2333,2434,2667,2636,2621,2674,2548,2685,2598,2751,2697,2634,2450,2125,2020,2132,2345,2510,2625,2501],[2564.651106803331,2554.234751135798,2569.687441484927,2559.245710557774,2574.723776166523,2564.256669979751,2579.760110848119,2569.267629401728,2584.796445529714,2574.278588823705,2589.83278021131,2579.289548245682,2594.869114892906,2584.300507667659,2599.905449574501,2589.311467089635,2604.941784256097,2594.322426511612,2609.978118937692,2599.333385933589,2615.014453619288,2604.344345355566,2620.050788300884,2609.355304777543,2625.087122982479,2614.36626419952,2630.123457664075,2619.377223621496,2635.159792345671,2624.388183043473,2640.196127027266,2629.39914246545,2645.232461708862,2634.410101887427,2650.268796390457,2639.421061309404,2655.305131072053,2644.432020731381,2660.341465753649,2649.442980153357,2665.377800435244,2654.453939575335,2670.41413511684,2659.464898997311,2675.450469798436,2664.475858419288,2680.486804480031,2669.486817841265,2685.523139161627,2674.497777263242,2690.559473843222,2679.508736685219,2695.595808524818],[2503.131704120522,2544.592955416814,2550.538215176896,2536.632125039567,2537.78045286741,2529.50538778286,2523.040763450706,2518.294038582212,2513.121743054865,2509.372230820087,2506.285404288154,2503.786436715624,2501.934860732399,2500.497555602001,2499.4278741525,2498.644986529514,2498.070572568226,2497.660575776662,2497.37014713985,2497.167156398043,2497.028130859934,2496.934223938763,2496.872210583837,2496.832309340804,2496.80742186093,2496.792605433549,2496.784360868137,2496.780290299478,2496.77877817836,2496.778748507723,2496.779509163151,2496.780626439442,2496.781839993303,2496.783003934428,2496.784044731344,2496.784933596593,2496.785667898659,2496.786259062121,2496.786725065584,2496.787085860095,2496.787360785393,2496.787567252736,2496.787720199088,2496.787832006576,2496.787912671213,2496.78797009053,2496.78801039125,2496.788038250271,2496.788057185704,2496.78806980781,2496.788078027692,2496.788083226274,2496.788086388115]],\"container\":\"<table class=\\\"table table-striped table-hover row-border order-column display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>Date<\\/th>\\n      <th>Confirmed<\\/th>\\n      <th>Forecast_HW<\\/th>\\n      <th>Forecast_MLP<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":[2,3,4]},{\"orderable\":false,\"targets\":0}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n:::\n\n::: {.content-visible when-format=\"pdf\"}\n\n::: {#tbl-forecastpdf .cell tbl-cap='Comparación de Resultados entre las técnicas y los datos reales para evaluar precisión'}\n::: {.cell-output .cell-output-stdout}\n\n```\n           Date Confirmed Forecast_HW Forecast_MLP\nt+1  2020-06-24      2445    2564.651     2503.132\nt+2  2020-06-25      2531    2554.235     2544.593\nt+3  2020-06-26      2595    2569.687     2550.538\nt+4  2020-06-27      2628    2559.246     2536.632\nt+5  2020-06-28      2456    2574.724     2537.780\nt+6  2020-06-29      2489    2564.257     2529.505\nt+7  2020-06-30      2536    2579.760     2523.041\nt+8  2020-07-01      2457    2569.268     2518.294\nt+9  2020-07-02      2549    2584.796     2513.122\nt+10 2020-07-03      2652    2574.279     2509.372\nt+11 2020-07-04      2566    2589.833     2506.285\nt+12 2020-07-05      2449    2579.290     2503.786\nt+13 2020-07-06      2560    2594.869     2501.935\nt+14 2020-07-07      2613    2584.301     2500.498\nt+15 2020-07-08      2637    2599.905     2499.428\nt+16 2020-07-09      2691    2589.311     2498.645\nt+17 2020-07-10      2079    2604.942     2498.071\nt+18 2020-07-11      2262    2594.322     2497.661\nt+19 2020-07-12      2397    2609.978     2497.370\nt+20 2020-07-13      2186    2599.333     2497.167\nt+21 2020-07-14      2349    2615.014     2497.028\nt+22 2020-07-15      2521    2604.344     2496.934\nt+23 2020-07-16      2388    2620.051     2496.872\nt+24 2020-07-17      2500    2609.355     2496.832\nt+25 2020-07-18      2379    2625.087     2496.807\nt+26 2020-07-19      2166    2614.366     2496.793\nt+27 2020-07-20      2182    2630.123     2496.784\nt+28 2020-07-21      2414    2619.377     2496.780\nt+29 2020-07-22      2625    2635.160     2496.779\nt+30 2020-07-23      2586    2624.388     2496.779\nt+31 2020-07-24      2621    2640.196     2496.780\nt+32 2020-07-25      2489    2629.399     2496.781\nt+33 2020-07-26      2316    2645.232     2496.782\nt+34 2020-07-27      2333    2634.410     2496.783\nt+35 2020-07-28      2434    2650.269     2496.784\nt+36 2020-07-29      2667    2639.421     2496.785\nt+37 2020-07-30      2636    2655.305     2496.786\nt+38 2020-07-31      2621    2644.432     2496.786\nt+39 2020-08-01      2674    2660.341     2496.787\nt+40 2020-08-02      2548    2649.443     2496.787\nt+41 2020-08-03      2685    2665.378     2496.787\nt+42 2020-08-04      2598    2654.454     2496.788\nt+43 2020-08-05      2751    2670.414     2496.788\nt+44 2020-08-06      2697    2659.465     2496.788\nt+45 2020-08-07      2634    2675.450     2496.788\nt+46 2020-08-08      2450    2664.476     2496.788\nt+47 2020-08-09      2125    2680.487     2496.788\nt+48 2020-08-10      2020    2669.487     2496.788\nt+49 2020-08-11      2132    2685.523     2496.788\nt+50 2020-08-12      2345    2674.498     2496.788\nt+51 2020-08-13      2510    2690.559     2496.788\nt+52 2020-08-14      2625    2679.509     2496.788\nt+53 2020-08-15      2501    2695.596     2496.788\n```\n\n\n:::\n:::\n\n:::\n\n::: {#fig-phw}\n\n::: {.cell}\n::: {.cell-output-display}\n![](confirmados_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\nPronóstico obtenido mediante la técnica de Holt-Winters.\n:::\n\n::: {#fig-pmlp}\n\n::: {.cell}\n::: {.cell-output-display}\n![](confirmados_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\nPronóstico obtenido mediante la red neuronal MLP.\n:::\n\n#### Métricas de rendimiento\n\n::: {style=\"text-align: justify\"}\nPara evaluar la calidad o bondad de ajuste de los métodos utilizados en este estudio y seleccionar el modelo más apropiado, se aplican tres métricas de rendimiento, Error Cuadrático Medio (@eq-RMSE), Error Absoluto Medio (@eq-MAE) y Error Porcentual Absoluto Medio (@eq-MAPE) tanto en las fases de entrenamiento como en las de prueba. Los resultados correspondientes a éstas métricas se presentan en la @tbl-err .\n\n\n::: {.cell}\n\n:::\n\n\n|                  |            |                |           |            |               |          |\n|------------------|:----------:|:--------------:|:---------:|:----------:|:-------------:|:--------:|\n|                  |            | ***Training*** |           |            | ***Testing*** |          |\n|                  |  **RMSE**  |    **MAE**     | **MAPE**  |  **RMSE**  |    **MAE**    | **MAPE** |\n| **Holt-Winters** | *262.9925* |   *190.0482*   | *20.8415* | *234.0094* |  *165.8208*   | *6.2967* |\n| **MLP**          | *239.3483* |   *180.9937*   | *14.6079* | *177.0605* |  *136.4799*   | *5.4441* |\n\n: Errores de los modelos para casos confirmados. {#tbl-err}\n:::\n\n### Conclusión\n\n::: {.content-visible when-format=\"html\"}\n::: {style=\"text-align: justify\"}\nBasándose en los resultados extraídos tanto de la tabla de pronósticos (@tbl-forecast) como de la tabla de errores (@tbl-err), se llega a la conclusión de que, para esta base de datos en particular, la técnica de redes neuronales MLP demuestra ser más efectiva en la predicción realizada. Esto se fundamenta en la evidencia de un menor error registrado en las tres métricas calculadas, tanto durante la fase de entrenamiento como en la fase de prueba.\n:::\n:::\n\n::: {.content-visible when-format=\"pdf\"}\n::: {style=\"text-align: justify\"}\nBasándose en los resultados extraídos tanto de la tabla de pronósticos (@tbl-forecastpdf) como de la tabla de errores (@tbl-err), se llega a la conclusión de que, para esta base de datos en particular, la técnica de redes neuronales MLP demuestra ser más efectiva en la predicción realizada. Esto se fundamenta en la evidencia de un menor error registrado en las tres métricas calculadas, tanto durante la fase de entrenamiento como en la fase de prueba.\n:::\n:::\n\n## Pronóstico de los próximos 30 días\n\n::: {.content-visible when-format=\"html\" style=\"text-align: justify\"}\nTras la identificación del modelo óptimo, se procedió a prever el comportamiento futuro de la serie temporal de casos confirmados para los próximos 30 días utilizando dicho modelo. Se elaboraron representaciones gráficas de la predicción de casos confirmados de COVID-19 a 30 días, realizando una comparación de la efectividad entre las implementaciones de redes neuronales en la paquetería de R y la paquetería nativa de Python, las cuales se encuentran en las figuras @fig-foremlp y @fig-mlp, respectivamente.\n:::\n\n::: {.content-visible when-format=\"pdf\" style=\"text-align: justify\"}\nTras la identificación del modelo óptimo, se procedió a prever el comportamiento futuro de la serie temporal de casos confirmados para los próximos 30 días utilizando dicho modelo. Se elaboraron representaciones gráficas de la predicción de casos confirmados de COVID-19 a 30 días, realizando una comparación de la efectividad entre las implementaciones de redes neuronales en la paquetería de R y la paquetería nativa de Python, las cuales se encuentran en las figuras @fig-foremlp y @fig-mlp1, respectivamente.\n:::\n\n### Implementación en R\n\n::: {style=\"text-align: justify\"}\nEn la implementación de R, siguiendo el mismo procedimiento que en las fases de entrenamiento y prueba, se empleó un número específico de capas y nodos ocultos determinados automáticamente a través del método de validación cruzada de 5 pliegues. Esta configuración se llevó a cabo con una función de activación sigmoide, ejecutando 20 iteraciones para el entrenamiento de la red neuronal.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit.mlp = mlp(ts(Confirmed_df$Confirmed), reps = 20, hd.auto.type = 'cv', \n              comb=\"median\")\nfore.mlp = forecast(fit.mlp, h = 30)\n```\n:::\n\n\n::: {#fig-foremlp}\n\n::: {.cell}\n::: {.cell-output-display}\n![](confirmados_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\nPredicción futura de la serie tiempo para infectados diariamente mediante el modelo MLP\n:::\n\n::: {.content-visible when-format=\"html\"}\n::: {style=\"text-align: justify\"}\nLos resultados del pronóstico indican que el 14 de septiembre de 2020 se proyectan aproximadamente 2494 nuevos casos confirmados de COVID-19. Estos valores correspondientes al período de 30 días se detallan a continuación en la @tbl-treinta .\n:::\n:::\n\n::: {.content-visible when-format=\"pdf\"}\n::: {style=\"text-align: justify\"}\nLos resultados del pronóstico indican que el 14 de septiembre de 2020 se proyectan aproximadamente 2494 nuevos casos confirmados de COVID-19. Estos valores correspondientes al período de 30 días se detallan a continuación en la @tbl-treintapdf .\n:::\n:::\n\n::: {.content-visible when-format=\"html\"}\n\n::: {#tbl-treinta .cell tbl-cap='Pronóstico de casos confirmados de COVID-19 en Irán en los próximos 30 días'}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item-overflow-hidden html-fill-item\" id=\"htmlwidget-fd5d45750148bf6f9b08\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-fd5d45750148bf6f9b08\">{\"x\":{\"style\":\"bootstrap4\",\"filter\":\"none\",\"vertical\":false,\"data\":[[\"t+1\",\"t+2\",\"t+3\",\"t+4\",\"t+5\",\"t+6\",\"t+7\",\"t+8\",\"t+9\",\"t+10\",\"t+11\",\"t+12\",\"t+13\",\"t+14\",\"t+15\",\"t+16\",\"t+17\",\"t+18\",\"t+19\",\"t+20\",\"t+21\",\"t+22\",\"t+23\",\"t+24\",\"t+25\",\"t+26\",\"t+27\",\"t+28\",\"t+29\",\"t+30\"],[\"2020-08-16\",\"2020-08-17\",\"2020-08-18\",\"2020-08-19\",\"2020-08-20\",\"2020-08-21\",\"2020-08-22\",\"2020-08-23\",\"2020-08-24\",\"2020-08-25\",\"2020-08-26\",\"2020-08-27\",\"2020-08-28\",\"2020-08-29\",\"2020-08-30\",\"2020-08-31\",\"2020-09-01\",\"2020-09-02\",\"2020-09-03\",\"2020-09-04\",\"2020-09-05\",\"2020-09-06\",\"2020-09-07\",\"2020-09-08\",\"2020-09-09\",\"2020-09-10\",\"2020-09-11\",\"2020-09-12\",\"2020-09-13\",\"2020-09-14\"],[2533.226,2518.436,2491.797,2485.9,2480.562,2476.452,2479.006,2479.376,2478.524,2478.593,2478.949,2479.673,2480.469,2481.212,2481.871,2482.391,2482.772,2483.029,2483.18,2481.891,2478.782,2477.86,2475.754,2476.439,2478.333,2479.371,2483.026,2483.002,2482.986,2482.977]],\"container\":\"<table class=\\\"table table-striped table-hover row-border order-column display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>Fecha<\\/th>\\n      <th>Infectados<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":2},{\"orderable\":false,\"targets\":0}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n:::\n\n::: {.content-visible when-format=\"pdf\"}\n\n::: {#tbl-treintapdf .cell tbl-cap='Pronóstico de casos confirmados de COVID-19 en Irán en los próximos 30 días'}\n::: {.cell-output .cell-output-stdout}\n\n```\n          Fecha Infectados\nt+1  2020-08-16   2533.226\nt+2  2020-08-17   2518.436\nt+3  2020-08-18   2491.797\nt+4  2020-08-19   2485.900\nt+5  2020-08-20   2480.562\nt+6  2020-08-21   2476.452\nt+7  2020-08-22   2479.006\nt+8  2020-08-23   2479.376\nt+9  2020-08-24   2478.524\nt+10 2020-08-25   2478.593\nt+11 2020-08-26   2478.949\nt+12 2020-08-27   2479.673\nt+13 2020-08-28   2480.469\nt+14 2020-08-29   2481.212\nt+15 2020-08-30   2481.871\nt+16 2020-08-31   2482.391\nt+17 2020-09-01   2482.772\nt+18 2020-09-02   2483.029\nt+19 2020-09-03   2483.180\nt+20 2020-09-04   2481.891\nt+21 2020-09-05   2478.782\nt+22 2020-09-06   2477.860\nt+23 2020-09-07   2475.754\nt+24 2020-09-08   2476.439\nt+25 2020-09-09   2478.333\nt+26 2020-09-10   2479.371\nt+27 2020-09-11   2483.026\nt+28 2020-09-12   2483.002\nt+29 2020-09-13   2482.986\nt+30 2020-09-14   2482.977\n```\n\n\n:::\n:::\n\n:::\n:::\n\n### Implementación en Python\n\n::: {style=\"text-align: justify\"}\nEn esta sección, se realizaron ajustes en el método para su implementación. Cada día proyectado se forma utilizando el dato del día anterior. En cada paso, se actualiza la secuencia de entrada eliminando el valor más antiguo e incorporando la predicción más reciente como el dato más reciente. Esta dinámica se representa esquemáticamente a continuación, donde $n$ representa la extensión de la secuencia de entrada y $T$ es la longitud de la serie temporal.\n\n$$\n\\begin{split}\ny:\\text{Observado}\\quad &\\quad \\hat{y}:\\text{Pronosticado}\\\\\ny_{T-n+1}\\quad y_{T-n+2}\\quad y_{T-n+3}\\quad&\\cdots\\quad y_{T-2}\\quad y_{T-1}\\quad y_T\\quad \\to\\quad \\hat{y}_{T+1}\\\\\ny_{T-n+2}\\quad y_{T-n+3}\\quad y_{T-n+4}\\quad&\\cdots\\quad y_{T-1}\\quad y_{T}\\quad \\hat{y}_{T+1}\\quad \\to\\quad \\hat{y}_{T+2}\\\\\ny_{T-n+3}\\quad y_{T-n+4}\\quad y_{T-n+5}\\quad&\\cdots\\quad y_{T}\\quad \\hat{y}_{T+1}\\quad \\hat{y}_{T+2}\\quad \\to\\quad \\hat{y}_{T+3}\\\\\n&\\ddots\\\\\n\\end{split}\n$$\n\nSe exhibe a continuación el código utilizado y el gráfico correspondiente al pronóstico generado por la red neuronal.\n:::\n\n::: {.content-visible when-format=\"html\"}\n::: {.callout-caution collapse=\"true\" icon=\"false\"}\n## ▸ Código\n\n``` python\nimport numpy as np\nimport pandas as pd\nimport yfinance as yf\nimport tensorflow as tf\nimport matplotlib.pyplot as plt\nimport plotly.express as px\nimport plotly.graph_objects as go\nfrom tensorflow.keras.layers import Dense, LSTM\nfrom tensorflow.keras.models import Sequential\nfrom sklearn.preprocessing import MinMaxScaler\n\npd.options.mode.chained_assignment = None\ntf.random.set_seed(0)\ndf = pd.read_excel('Data.xlsx')\n\n# ------------- Entrenamiento y prueba del modelo --------------\ny = df['Confirmed'].fillna(method='ffill')\ny = y.values.reshape(-1, 1)\n# scale the data\nscaler = MinMaxScaler(feature_range=(0, 1))\nscaler = scaler.fit(y)\ny = scaler.transform(y)\n\n# generate the input and output sequences\nn_lookback = 53  # length of input sequences (lookback period)\nn_forecast = 30  # length of output sequences (forecast period)\n\nX = []\nY = []\n\nfor i in range(n_lookback, len(y) - n_forecast + 1):\n    X.append(y[i - n_lookback: i])\n    Y.append(y[i: i + n_forecast])\n\nX = np.array(X)\nY = np.array(Y)\n\n# fit the model\nmodel = Sequential()\nmodel.add(Dense(20, activation='sigmoid', input_dim=n_lookback))\nmodel.add(Dense(n_forecast))\n\nmodel.compile(loss='mean_squared_error', optimizer='adam')\nmodel.fit(X, Y, epochs=20, batch_size=4, verbose=0)\n\n# generate the forecasts\nX_ = y[- n_lookback:]  # last available input sequence\nX_ = X_.reshape(1, n_lookback, 1)\n\nY_ = model.predict(X_).reshape(-1, 1)\nY_ = scaler.inverse_transform(Y_)\n\n# organize the results in a data frame\ndf_past = df\ndf_past.rename(columns={'Date':'Date','Confirmed':'Actual'},inplace=True)\ndf_past['Date'] = pd.to_datetime(df_past['Date'])\ndf_past['Forecast'] = np.nan\ndf_past['Forecast'].iloc[-1] = df_past['Actual'].iloc[-1]\n\ndf_future = pd.DataFrame(columns=['Date', 'Actual', 'Forecast'])\ndf_future['Date'] = pd.date_range(\n  start=df_past['Date'].iloc[-1] + pd.Timedelta(days=1), \n  periods=n_forecast)\ndf_future['Forecast'] = Y_.flatten()\ndf_future['Actual'] = np.nan\n\nresults = df_past._append(df_future).set_index('Date')\n# Calculate minimum, median, and maximum for each forecasted date\nresults['Min'] = results['Forecast'].rolling(window=2).min()\nresults['Max'] = results['Forecast'].rolling(window=2).max()\nresults['Median'] = results['Forecast'].rolling(window=2).median()\n\n# Creamos la gráfica con las predicciones\n#fig = px.line(results, x=results.index, y=['Actual','Forecast', 'Median'],\nfig = px.line(results, x=results.index, y=['Actual', 'Median'],\n              labels={'index': 'Date', 'value': 'Confirmed Cases'},\n              title='Casos Confirmados',\n              line_shape='linear')\n\nfig.update_traces(line=dict(color='cornflowerblue'), \nselector=dict(name='Actual'))\nfig.update_traces(line=dict(color='orange'), \nselector=dict(name='Forecast'))\nfig.update_traces(line=dict(color='mediumvioletred'), \nselector=dict(name='Median'))\n\n# Agregar gráficos de área para el mínimo y el máximo\nfig.add_trace(\n    go.Scatter(x=results.index, \n    y=results['Min'], \n    fill=None, mode='lines', \n    line=dict(color='hotpink'), \n    name='Min'))\nfig.add_trace(\n    go.Scatter(x=results.index, \n    y=results['Max'], \n    fill='tonexty', \n    mode='lines', \n    line=dict(color='deeppink'), \n    name='Max'))\nfig.show('')\n```\n:::\n:::\n\n::: {.content-visible when-format=\"pdf\"}\n``` python\nimport numpy as np\nimport pandas as pd\nimport yfinance as yf\nimport tensorflow as tf\nimport matplotlib.pyplot as plt\nimport plotly.express as px\nimport plotly.graph_objects as go\nfrom tensorflow.keras.layers import Dense, LSTM\nfrom tensorflow.keras.models import Sequential\nfrom sklearn.preprocessing import MinMaxScaler\n\npd.options.mode.chained_assignment = None\ntf.random.set_seed(0)\ndf = pd.read_excel('Data.xlsx')\n\n# ------------- Entrenamiento y prueba del modelo --------------\ny = df['Confirmed'].fillna(method='ffill')\ny = y.values.reshape(-1, 1)\n# scale the data\nscaler = MinMaxScaler(feature_range=(0, 1))\nscaler = scaler.fit(y)\ny = scaler.transform(y)\n\n# generate the input and output sequences\nn_lookback = 53  # length of input sequences (lookback period)\nn_forecast = 30  # length of output sequences (forecast period)\n\nX = []\nY = []\n\nfor i in range(n_lookback, len(y) - n_forecast + 1):\n    X.append(y[i - n_lookback: i])\n    Y.append(y[i: i + n_forecast])\n\nX = np.array(X)\nY = np.array(Y)\n\n# fit the model\nmodel = Sequential()\nmodel.add(Dense(20, activation='sigmoid', input_dim=n_lookback))\nmodel.add(Dense(n_forecast))\n\nmodel.compile(loss='mean_squared_error', optimizer='adam')\nmodel.fit(X, Y, epochs=20, batch_size=4, verbose=0)\n\n# generate the forecasts\nX_ = y[- n_lookback:]  # last available input sequence\nX_ = X_.reshape(1, n_lookback, 1)\n\nY_ = model.predict(X_).reshape(-1, 1)\nY_ = scaler.inverse_transform(Y_)\n\n# organize the results in a data frame\ndf_past = df\ndf_past.rename(columns={'Date': 'Date', 'Confirmed': 'Actual'}, inplace=True)\ndf_past['Date'] = pd.to_datetime(df_past['Date'])\ndf_past['Forecast'] = np.nan\ndf_past['Forecast'].iloc[-1] = df_past['Actual'].iloc[-1]\n\ndf_future = pd.DataFrame(columns=['Date', 'Actual', 'Forecast'])\ndf_future['Date'] = pd.date_range(\n  start=df_past['Date'].iloc[-1] + pd.Timedelta(days=1), \n  periods=n_forecast)\ndf_future['Forecast'] = Y_.flatten()\ndf_future['Actual'] = np.nan\n\nresults = df_past._append(df_future).set_index('Date')\n# Calculate minimum, median, and maximum for each forecasted date\nresults['Min'] = results['Forecast'].rolling(window=2).min()\nresults['Max'] = results['Forecast'].rolling(window=2).max()\nresults['Median'] = results['Forecast'].rolling(window=2).median()\n\n# Creamos la gráfica con las predicciones\n#fig = px.line(results, x=results.index, y=['Actual','Forecast', 'Median'],\nfig = px.line(results, x=results.index, y=['Actual', 'Median'],\n              labels={'index': 'Date', 'value': 'Confirmed Cases'},\n              title='Casos Confirmados',\n              line_shape='linear')\n\nfig.update_traces(line=dict(color='cornflowerblue'), \nselector=dict(name='Actual'))\nfig.update_traces(line=dict(color='orange'), \nselector=dict(name='Forecast'))\nfig.update_traces(line=dict(color='mediumvioletred'), \nselector=dict(name='Median'))\n\n# Agregar gráficos de área para el mínimo y el máximo\nfig.add_trace(\n    go.Scatter(x=results.index, \n    y=results['Min'], \n    fill=None, mode='lines', \n    line=dict(color='hotpink'), \n    name='Min'))\nfig.add_trace(\n    go.Scatter(x=results.index, \n    y=results['Max'], \n    fill='tonexty', \n    mode='lines', \n    line=dict(color='deeppink'), \n    name='Max'))\nfig.show('')\n```\n:::\n\n::: {.content-visible when-format=\"html\"}\n\n\n\n:::\n\n::: {.content-visible when-format=\"html\"}\n\n::: {.cell}\n::: {#fig-mlp .cell-output-display}\n\n```{=html}\n<div>                        <script type=\"text/javascript\">window.PlotlyConfig = {MathJaxConfig: 'local'};</script>\n        <script charset=\"utf-8\" src=\"https://cdn.plot.ly/plotly-2.27.0.min.js\"></script>                <div id=\"688446ba-215e-4263-bb91-bcb784824071\" class=\"plotly-graph-div\" style=\"height:100%; width:100%;\"></div>            <script type=\"text/javascript\">                                    window.PLOTLYENV=window.PLOTLYENV || {};                                    if (document.getElementById(\"688446ba-215e-4263-bb91-bcb784824071\")) {                    Plotly.newPlot(                        \"688446ba-215e-4263-bb91-bcb784824071\",                        [{\"hovertemplate\":\"variable=Actual\\u003cbr\\u003eDate=%{x}\\u003cbr\\u003eConfirmed Cases=%{y}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"legendgroup\":\"Actual\",\"line\":{\"color\":\"cornflowerblue\",\"dash\":\"solid\",\"shape\":\"linear\"},\"marker\":{\"symbol\":\"circle\"},\"mode\":\"lines\",\"name\":\"Actual\",\"orientation\":\"v\",\"showlegend\":true,\"x\":[\"2020-02-20T00:00:00\",\"2020-02-21T00:00:00\",\"2020-02-22T00:00:00\",\"2020-02-23T00:00:00\",\"2020-02-24T00:00:00\",\"2020-02-25T00:00:00\",\"2020-02-26T00:00:00\",\"2020-02-27T00:00:00\",\"2020-02-28T00:00:00\",\"2020-02-29T00:00:00\",\"2020-03-01T00:00:00\",\"2020-03-02T00:00:00\",\"2020-03-03T00:00:00\",\"2020-03-04T00:00:00\",\"2020-03-05T00:00:00\",\"2020-03-06T00:00:00\",\"2020-03-07T00:00:00\",\"2020-03-08T00:00:00\",\"2020-03-09T00:00:00\",\"2020-03-10T00:00:00\",\"2020-03-11T00:00:00\",\"2020-03-12T00:00:00\",\"2020-03-13T00:00:00\",\"2020-03-14T00:00:00\",\"2020-03-15T00:00:00\",\"2020-03-16T00:00:00\",\"2020-03-17T00:00:00\",\"2020-03-18T00:00:00\",\"2020-03-19T00:00:00\",\"2020-03-20T00:00:00\",\"2020-03-21T00:00:00\",\"2020-03-22T00:00:00\",\"2020-03-23T00:00:00\",\"2020-03-24T00:00:00\",\"2020-03-25T00:00:00\",\"2020-03-26T00:00:00\",\"2020-03-27T00:00:00\",\"2020-03-28T00:00:00\",\"2020-03-29T00:00:00\",\"2020-03-30T00:00:00\",\"2020-03-31T00:00:00\",\"2020-04-01T00:00:00\",\"2020-04-02T00:00:00\",\"2020-04-03T00:00:00\",\"2020-04-04T00:00:00\",\"2020-04-05T00:00:00\",\"2020-04-06T00:00:00\",\"2020-04-07T00:00:00\",\"2020-04-08T00:00:00\",\"2020-04-09T00:00:00\",\"2020-04-10T00:00:00\",\"2020-04-11T00:00:00\",\"2020-04-12T00:00:00\",\"2020-04-13T00:00:00\",\"2020-04-14T00:00:00\",\"2020-04-15T00:00:00\",\"2020-04-16T00:00:00\",\"2020-04-17T00:00:00\",\"2020-04-18T00:00:00\",\"2020-04-19T00:00:00\",\"2020-04-20T00:00:00\",\"2020-04-21T00:00:00\",\"2020-04-22T00:00:00\",\"2020-04-23T00:00:00\",\"2020-04-24T00:00:00\",\"2020-04-25T00:00:00\",\"2020-04-26T00:00:00\",\"2020-04-27T00:00:00\",\"2020-04-28T00:00:00\",\"2020-04-29T00:00:00\",\"2020-04-30T00:00:00\",\"2020-05-01T00:00:00\",\"2020-05-02T00:00:00\",\"2020-05-03T00:00:00\",\"2020-05-04T00:00:00\",\"2020-05-05T00:00:00\",\"2020-05-06T00:00:00\",\"2020-05-07T00:00:00\",\"2020-05-08T00:00:00\",\"2020-05-09T00:00:00\",\"2020-05-10T00:00:00\",\"2020-05-11T00:00:00\",\"2020-05-12T00:00:00\",\"2020-05-13T00:00:00\",\"2020-05-14T00:00:00\",\"2020-05-15T00:00:00\",\"2020-05-16T00:00:00\",\"2020-05-17T00:00:00\",\"2020-05-18T00:00:00\",\"2020-05-19T00:00:00\",\"2020-05-20T00:00:00\",\"2020-05-21T00:00:00\",\"2020-05-22T00:00:00\",\"2020-05-23T00:00:00\",\"2020-05-24T00:00:00\",\"2020-05-25T00:00:00\",\"2020-05-26T00:00:00\",\"2020-05-27T00:00:00\",\"2020-05-28T00:00:00\",\"2020-05-29T00:00:00\",\"2020-05-30T00:00:00\",\"2020-05-31T00:00:00\",\"2020-06-01T00:00:00\",\"2020-06-02T00:00:00\",\"2020-06-03T00:00:00\",\"2020-06-04T00:00:00\",\"2020-06-05T00:00:00\",\"2020-06-06T00:00:00\",\"2020-06-07T00:00:00\",\"2020-06-08T00:00:00\",\"2020-06-09T00:00:00\",\"2020-06-10T00:00:00\",\"2020-06-11T00:00:00\",\"2020-06-12T00:00:00\",\"2020-06-13T00:00:00\",\"2020-06-14T00:00:00\",\"2020-06-15T00:00:00\",\"2020-06-16T00:00:00\",\"2020-06-17T00:00:00\",\"2020-06-18T00:00:00\",\"2020-06-19T00:00:00\",\"2020-06-20T00:00:00\",\"2020-06-21T00:00:00\",\"2020-06-22T00:00:00\",\"2020-06-23T00:00:00\",\"2020-06-24T00:00:00\",\"2020-06-25T00:00:00\",\"2020-06-26T00:00:00\",\"2020-06-27T00:00:00\",\"2020-06-28T00:00:00\",\"2020-06-29T00:00:00\",\"2020-06-30T00:00:00\",\"2020-07-01T00:00:00\",\"2020-07-02T00:00:00\",\"2020-07-03T00:00:00\",\"2020-07-04T00:00:00\",\"2020-07-05T00:00:00\",\"2020-07-06T00:00:00\",\"2020-07-07T00:00:00\",\"2020-07-08T00:00:00\",\"2020-07-09T00:00:00\",\"2020-07-10T00:00:00\",\"2020-07-11T00:00:00\",\"2020-07-12T00:00:00\",\"2020-07-13T00:00:00\",\"2020-07-14T00:00:00\",\"2020-07-15T00:00:00\",\"2020-07-16T00:00:00\",\"2020-07-17T00:00:00\",\"2020-07-18T00:00:00\",\"2020-07-19T00:00:00\",\"2020-07-20T00:00:00\",\"2020-07-21T00:00:00\",\"2020-07-22T00:00:00\",\"2020-07-23T00:00:00\",\"2020-07-24T00:00:00\",\"2020-07-25T00:00:00\",\"2020-07-26T00:00:00\",\"2020-07-27T00:00:00\",\"2020-07-28T00:00:00\",\"2020-07-29T00:00:00\",\"2020-07-30T00:00:00\",\"2020-07-31T00:00:00\",\"2020-08-01T00:00:00\",\"2020-08-02T00:00:00\",\"2020-08-03T00:00:00\",\"2020-08-04T00:00:00\",\"2020-08-05T00:00:00\",\"2020-08-06T00:00:00\",\"2020-08-07T00:00:00\",\"2020-08-08T00:00:00\",\"2020-08-09T00:00:00\",\"2020-08-10T00:00:00\",\"2020-08-11T00:00:00\",\"2020-08-12T00:00:00\",\"2020-08-13T00:00:00\",\"2020-08-14T00:00:00\",\"2020-08-15T00:00:00\",\"2020-08-16T00:00:00\",\"2020-08-17T00:00:00\",\"2020-08-18T00:00:00\",\"2020-08-19T00:00:00\",\"2020-08-20T00:00:00\",\"2020-08-21T00:00:00\",\"2020-08-22T00:00:00\",\"2020-08-23T00:00:00\",\"2020-08-24T00:00:00\",\"2020-08-25T00:00:00\",\"2020-08-26T00:00:00\",\"2020-08-27T00:00:00\",\"2020-08-28T00:00:00\",\"2020-08-29T00:00:00\",\"2020-08-30T00:00:00\",\"2020-08-31T00:00:00\",\"2020-09-01T00:00:00\",\"2020-09-02T00:00:00\",\"2020-09-03T00:00:00\",\"2020-09-04T00:00:00\",\"2020-09-05T00:00:00\",\"2020-09-06T00:00:00\",\"2020-09-07T00:00:00\",\"2020-09-08T00:00:00\",\"2020-09-09T00:00:00\",\"2020-09-10T00:00:00\",\"2020-09-11T00:00:00\",\"2020-09-12T00:00:00\",\"2020-09-13T00:00:00\",\"2020-09-14T00:00:00\"],\"xaxis\":\"x\",\"y\":[3.0,13.0,10.0,15.0,4.0,48.0,44.0,146.5,249.0,227.0,205.0,556.5,908.0,1421.0,591.0,1234.0,1076.0,743.0,595.0,881.0,958.0,1075.0,1289.0,1365.0,1254.0,1008.0,1178.0,1192.0,1046.0,1233.0,966.0,1028.0,1411.0,1762.0,2206.0,2389.0,2926.0,3076.0,2901.0,3186.0,3111.0,2987.0,2875.0,2715.0,2560.0,2521.5,2483.0,2274.0,2089.0,1997.0,1634.0,1972.0,1837.0,1657.0,1617.0,1574.0,1512.0,1606.0,1499.0,1374.0,1343.0,1294.0,1297.0,1194.0,1030.0,1168.0,1134.0,1153.0,991.0,1112.0,1073.0,983.0,1006.0,802.0,976.0,1223.0,1323.0,1680.0,1485.0,1556.0,1529.0,1383.0,1683.0,1481.0,1958.0,1808.0,2102.0,1757.0,1806.0,2294.0,2111.0,2346.0,2392.0,2311.0,1869.0,2180.0,2023.0,1787.0,2080.0,2258.0,2819.0,2282.0,2516.0,2979.0,3117.0,3134.0,3574.0,2886.0,2269.0,2364.0,2043.0,2095.0,2011.0,2238.0,2369.0,2410.0,2472.0,2449.0,2563.0,2612.0,2596.0,2615.0,2322.0,2368.0,2573.0,2445.0,2531.0,2595.0,2628.0,2456.0,2489.0,2536.0,2457.0,2549.0,2652.0,2566.0,2449.0,2560.0,2613.0,2637.0,2691.0,2079.0,2262.0,2397.0,2186.0,2349.0,2521.0,2388.0,2500.0,2379.0,2166.0,2182.0,2414.0,2625.0,2586.0,2621.0,2489.0,2316.0,2333.0,2434.0,2667.0,2636.0,2621.0,2674.0,2548.0,2685.0,2598.0,2751.0,2697.0,2634.0,2450.0,2125.0,2020.0,2132.0,2345.0,2510.0,2625.0,2501.0,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],\"yaxis\":\"y\",\"type\":\"scatter\"},{\"hovertemplate\":\"variable=Median\\u003cbr\\u003eDate=%{x}\\u003cbr\\u003eConfirmed Cases=%{y}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"legendgroup\":\"Median\",\"line\":{\"color\":\"mediumvioletred\",\"dash\":\"solid\",\"shape\":\"linear\"},\"marker\":{\"symbol\":\"circle\"},\"mode\":\"lines\",\"name\":\"Median\",\"orientation\":\"v\",\"showlegend\":true,\"x\":[\"2020-02-20T00:00:00\",\"2020-02-21T00:00:00\",\"2020-02-22T00:00:00\",\"2020-02-23T00:00:00\",\"2020-02-24T00:00:00\",\"2020-02-25T00:00:00\",\"2020-02-26T00:00:00\",\"2020-02-27T00:00:00\",\"2020-02-28T00:00:00\",\"2020-02-29T00:00:00\",\"2020-03-01T00:00:00\",\"2020-03-02T00:00:00\",\"2020-03-03T00:00:00\",\"2020-03-04T00:00:00\",\"2020-03-05T00:00:00\",\"2020-03-06T00:00:00\",\"2020-03-07T00:00:00\",\"2020-03-08T00:00:00\",\"2020-03-09T00:00:00\",\"2020-03-10T00:00:00\",\"2020-03-11T00:00:00\",\"2020-03-12T00:00:00\",\"2020-03-13T00:00:00\",\"2020-03-14T00:00:00\",\"2020-03-15T00:00:00\",\"2020-03-16T00:00:00\",\"2020-03-17T00:00:00\",\"2020-03-18T00:00:00\",\"2020-03-19T00:00:00\",\"2020-03-20T00:00:00\",\"2020-03-21T00:00:00\",\"2020-03-22T00:00:00\",\"2020-03-23T00:00:00\",\"2020-03-24T00:00:00\",\"2020-03-25T00:00:00\",\"2020-03-26T00:00:00\",\"2020-03-27T00:00:00\",\"2020-03-28T00:00:00\",\"2020-03-29T00:00:00\",\"2020-03-30T00:00:00\",\"2020-03-31T00:00:00\",\"2020-04-01T00:00:00\",\"2020-04-02T00:00:00\",\"2020-04-03T00:00:00\",\"2020-04-04T00:00:00\",\"2020-04-05T00:00:00\",\"2020-04-06T00:00:00\",\"2020-04-07T00:00:00\",\"2020-04-08T00:00:00\",\"2020-04-09T00:00:00\",\"2020-04-10T00:00:00\",\"2020-04-11T00:00:00\",\"2020-04-12T00:00:00\",\"2020-04-13T00:00:00\",\"2020-04-14T00:00:00\",\"2020-04-15T00:00:00\",\"2020-04-16T00:00:00\",\"2020-04-17T00:00:00\",\"2020-04-18T00:00:00\",\"2020-04-19T00:00:00\",\"2020-04-20T00:00:00\",\"2020-04-21T00:00:00\",\"2020-04-22T00:00:00\",\"2020-04-23T00:00:00\",\"2020-04-24T00:00:00\",\"2020-04-25T00:00:00\",\"2020-04-26T00:00:00\",\"2020-04-27T00:00:00\",\"2020-04-28T00:00:00\",\"2020-04-29T00:00:00\",\"2020-04-30T00:00:00\",\"2020-05-01T00:00:00\",\"2020-05-02T00:00:00\",\"2020-05-03T00:00:00\",\"2020-05-04T00:00:00\",\"2020-05-05T00:00:00\",\"2020-05-06T00:00:00\",\"2020-05-07T00:00:00\",\"2020-05-08T00:00:00\",\"2020-05-09T00:00:00\",\"2020-05-10T00:00:00\",\"2020-05-11T00:00:00\",\"2020-05-12T00:00:00\",\"2020-05-13T00:00:00\",\"2020-05-14T00:00:00\",\"2020-05-15T00:00:00\",\"2020-05-16T00:00:00\",\"2020-05-17T00:00:00\",\"2020-05-18T00:00:00\",\"2020-05-19T00:00:00\",\"2020-05-20T00:00:00\",\"2020-05-21T00:00:00\",\"2020-05-22T00:00:00\",\"2020-05-23T00:00:00\",\"2020-05-24T00:00:00\",\"2020-05-25T00:00:00\",\"2020-05-26T00:00:00\",\"2020-05-27T00:00:00\",\"2020-05-28T00:00:00\",\"2020-05-29T00:00:00\",\"2020-05-30T00:00:00\",\"2020-05-31T00:00:00\",\"2020-06-01T00:00:00\",\"2020-06-02T00:00:00\",\"2020-06-03T00:00:00\",\"2020-06-04T00:00:00\",\"2020-06-05T00:00:00\",\"2020-06-06T00:00:00\",\"2020-06-07T00:00:00\",\"2020-06-08T00:00:00\",\"2020-06-09T00:00:00\",\"2020-06-10T00:00:00\",\"2020-06-11T00:00:00\",\"2020-06-12T00:00:00\",\"2020-06-13T00:00:00\",\"2020-06-14T00:00:00\",\"2020-06-15T00:00:00\",\"2020-06-16T00:00:00\",\"2020-06-17T00:00:00\",\"2020-06-18T00:00:00\",\"2020-06-19T00:00:00\",\"2020-06-20T00:00:00\",\"2020-06-21T00:00:00\",\"2020-06-22T00:00:00\",\"2020-06-23T00:00:00\",\"2020-06-24T00:00:00\",\"2020-06-25T00:00:00\",\"2020-06-26T00:00:00\",\"2020-06-27T00:00:00\",\"2020-06-28T00:00:00\",\"2020-06-29T00:00:00\",\"2020-06-30T00:00:00\",\"2020-07-01T00:00:00\",\"2020-07-02T00:00:00\",\"2020-07-03T00:00:00\",\"2020-07-04T00:00:00\",\"2020-07-05T00:00:00\",\"2020-07-06T00:00:00\",\"2020-07-07T00:00:00\",\"2020-07-08T00:00:00\",\"2020-07-09T00:00:00\",\"2020-07-10T00:00:00\",\"2020-07-11T00:00:00\",\"2020-07-12T00:00:00\",\"2020-07-13T00:00:00\",\"2020-07-14T00:00:00\",\"2020-07-15T00:00:00\",\"2020-07-16T00:00:00\",\"2020-07-17T00:00:00\",\"2020-07-18T00:00:00\",\"2020-07-19T00:00:00\",\"2020-07-20T00:00:00\",\"2020-07-21T00:00:00\",\"2020-07-22T00:00:00\",\"2020-07-23T00:00:00\",\"2020-07-24T00:00:00\",\"2020-07-25T00:00:00\",\"2020-07-26T00:00:00\",\"2020-07-27T00:00:00\",\"2020-07-28T00:00:00\",\"2020-07-29T00:00:00\",\"2020-07-30T00:00:00\",\"2020-07-31T00:00:00\",\"2020-08-01T00:00:00\",\"2020-08-02T00:00:00\",\"2020-08-03T00:00:00\",\"2020-08-04T00:00:00\",\"2020-08-05T00:00:00\",\"2020-08-06T00:00:00\",\"2020-08-07T00:00:00\",\"2020-08-08T00:00:00\",\"2020-08-09T00:00:00\",\"2020-08-10T00:00:00\",\"2020-08-11T00:00:00\",\"2020-08-12T00:00:00\",\"2020-08-13T00:00:00\",\"2020-08-14T00:00:00\",\"2020-08-15T00:00:00\",\"2020-08-16T00:00:00\",\"2020-08-17T00:00:00\",\"2020-08-18T00:00:00\",\"2020-08-19T00:00:00\",\"2020-08-20T00:00:00\",\"2020-08-21T00:00:00\",\"2020-08-22T00:00:00\",\"2020-08-23T00:00:00\",\"2020-08-24T00:00:00\",\"2020-08-25T00:00:00\",\"2020-08-26T00:00:00\",\"2020-08-27T00:00:00\",\"2020-08-28T00:00:00\",\"2020-08-29T00:00:00\",\"2020-08-30T00:00:00\",\"2020-08-31T00:00:00\",\"2020-09-01T00:00:00\",\"2020-09-02T00:00:00\",\"2020-09-03T00:00:00\",\"2020-09-04T00:00:00\",\"2020-09-05T00:00:00\",\"2020-09-06T00:00:00\",\"2020-09-07T00:00:00\",\"2020-09-08T00:00:00\",\"2020-09-09T00:00:00\",\"2020-09-10T00:00:00\",\"2020-09-11T00:00:00\",\"2020-09-12T00:00:00\",\"2020-09-13T00:00:00\",\"2020-09-14T00:00:00\"],\"xaxis\":\"x\",\"y\":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,2350.203857421875,2212.470458984375,2255.0118408203125,2356.881103515625,2379.768798828125,2245.841552734375,2171.0745849609375,2314.5950927734375,2279.173095703125,2243.8997802734375,2375.510009765625,2376.8585205078125,2518.0501708984375,2518.391357421875,2464.3480224609375,2480.7545166015625,2454.6248779296875,2597.735107421875,2654.7506103515625,2578.390625,2477.5311279296875,2493.228271484375,2663.9505615234375,2646.3868408203125,2592.64013671875,2661.85595703125,2691.490478515625,2624.4949951171875,2606.4239501953125,2667.8511962890625],\"yaxis\":\"y\",\"type\":\"scatter\"},{\"line\":{\"color\":\"hotpink\"},\"mode\":\"lines\",\"name\":\"Min\",\"x\":[\"2020-02-20T00:00:00\",\"2020-02-21T00:00:00\",\"2020-02-22T00:00:00\",\"2020-02-23T00:00:00\",\"2020-02-24T00:00:00\",\"2020-02-25T00:00:00\",\"2020-02-26T00:00:00\",\"2020-02-27T00:00:00\",\"2020-02-28T00:00:00\",\"2020-02-29T00:00:00\",\"2020-03-01T00:00:00\",\"2020-03-02T00:00:00\",\"2020-03-03T00:00:00\",\"2020-03-04T00:00:00\",\"2020-03-05T00:00:00\",\"2020-03-06T00:00:00\",\"2020-03-07T00:00:00\",\"2020-03-08T00:00:00\",\"2020-03-09T00:00:00\",\"2020-03-10T00:00:00\",\"2020-03-11T00:00:00\",\"2020-03-12T00:00:00\",\"2020-03-13T00:00:00\",\"2020-03-14T00:00:00\",\"2020-03-15T00:00:00\",\"2020-03-16T00:00:00\",\"2020-03-17T00:00:00\",\"2020-03-18T00:00:00\",\"2020-03-19T00:00:00\",\"2020-03-20T00:00:00\",\"2020-03-21T00:00:00\",\"2020-03-22T00:00:00\",\"2020-03-23T00:00:00\",\"2020-03-24T00:00:00\",\"2020-03-25T00:00:00\",\"2020-03-26T00:00:00\",\"2020-03-27T00:00:00\",\"2020-03-28T00:00:00\",\"2020-03-29T00:00:00\",\"2020-03-30T00:00:00\",\"2020-03-31T00:00:00\",\"2020-04-01T00:00:00\",\"2020-04-02T00:00:00\",\"2020-04-03T00:00:00\",\"2020-04-04T00:00:00\",\"2020-04-05T00:00:00\",\"2020-04-06T00:00:00\",\"2020-04-07T00:00:00\",\"2020-04-08T00:00:00\",\"2020-04-09T00:00:00\",\"2020-04-10T00:00:00\",\"2020-04-11T00:00:00\",\"2020-04-12T00:00:00\",\"2020-04-13T00:00:00\",\"2020-04-14T00:00:00\",\"2020-04-15T00:00:00\",\"2020-04-16T00:00:00\",\"2020-04-17T00:00:00\",\"2020-04-18T00:00:00\",\"2020-04-19T00:00:00\",\"2020-04-20T00:00:00\",\"2020-04-21T00:00:00\",\"2020-04-22T00:00:00\",\"2020-04-23T00:00:00\",\"2020-04-24T00:00:00\",\"2020-04-25T00:00:00\",\"2020-04-26T00:00:00\",\"2020-04-27T00:00:00\",\"2020-04-28T00:00:00\",\"2020-04-29T00:00:00\",\"2020-04-30T00:00:00\",\"2020-05-01T00:00:00\",\"2020-05-02T00:00:00\",\"2020-05-03T00:00:00\",\"2020-05-04T00:00:00\",\"2020-05-05T00:00:00\",\"2020-05-06T00:00:00\",\"2020-05-07T00:00:00\",\"2020-05-08T00:00:00\",\"2020-05-09T00:00:00\",\"2020-05-10T00:00:00\",\"2020-05-11T00:00:00\",\"2020-05-12T00:00:00\",\"2020-05-13T00:00:00\",\"2020-05-14T00:00:00\",\"2020-05-15T00:00:00\",\"2020-05-16T00:00:00\",\"2020-05-17T00:00:00\",\"2020-05-18T00:00:00\",\"2020-05-19T00:00:00\",\"2020-05-20T00:00:00\",\"2020-05-21T00:00:00\",\"2020-05-22T00:00:00\",\"2020-05-23T00:00:00\",\"2020-05-24T00:00:00\",\"2020-05-25T00:00:00\",\"2020-05-26T00:00:00\",\"2020-05-27T00:00:00\",\"2020-05-28T00:00:00\",\"2020-05-29T00:00:00\",\"2020-05-30T00:00:00\",\"2020-05-31T00:00:00\",\"2020-06-01T00:00:00\",\"2020-06-02T00:00:00\",\"2020-06-03T00:00:00\",\"2020-06-04T00:00:00\",\"2020-06-05T00:00:00\",\"2020-06-06T00:00:00\",\"2020-06-07T00:00:00\",\"2020-06-08T00:00:00\",\"2020-06-09T00:00:00\",\"2020-06-10T00:00:00\",\"2020-06-11T00:00:00\",\"2020-06-12T00:00:00\",\"2020-06-13T00:00:00\",\"2020-06-14T00:00:00\",\"2020-06-15T00:00:00\",\"2020-06-16T00:00:00\",\"2020-06-17T00:00:00\",\"2020-06-18T00:00:00\",\"2020-06-19T00:00:00\",\"2020-06-20T00:00:00\",\"2020-06-21T00:00:00\",\"2020-06-22T00:00:00\",\"2020-06-23T00:00:00\",\"2020-06-24T00:00:00\",\"2020-06-25T00:00:00\",\"2020-06-26T00:00:00\",\"2020-06-27T00:00:00\",\"2020-06-28T00:00:00\",\"2020-06-29T00:00:00\",\"2020-06-30T00:00:00\",\"2020-07-01T00:00:00\",\"2020-07-02T00:00:00\",\"2020-07-03T00:00:00\",\"2020-07-04T00:00:00\",\"2020-07-05T00:00:00\",\"2020-07-06T00:00:00\",\"2020-07-07T00:00:00\",\"2020-07-08T00:00:00\",\"2020-07-09T00:00:00\",\"2020-07-10T00:00:00\",\"2020-07-11T00:00:00\",\"2020-07-12T00:00:00\",\"2020-07-13T00:00:00\",\"2020-07-14T00:00:00\",\"2020-07-15T00:00:00\",\"2020-07-16T00:00:00\",\"2020-07-17T00:00:00\",\"2020-07-18T00:00:00\",\"2020-07-19T00:00:00\",\"2020-07-20T00:00:00\",\"2020-07-21T00:00:00\",\"2020-07-22T00:00:00\",\"2020-07-23T00:00:00\",\"2020-07-24T00:00:00\",\"2020-07-25T00:00:00\",\"2020-07-26T00:00:00\",\"2020-07-27T00:00:00\",\"2020-07-28T00:00:00\",\"2020-07-29T00:00:00\",\"2020-07-30T00:00:00\",\"2020-07-31T00:00:00\",\"2020-08-01T00:00:00\",\"2020-08-02T00:00:00\",\"2020-08-03T00:00:00\",\"2020-08-04T00:00:00\",\"2020-08-05T00:00:00\",\"2020-08-06T00:00:00\",\"2020-08-07T00:00:00\",\"2020-08-08T00:00:00\",\"2020-08-09T00:00:00\",\"2020-08-10T00:00:00\",\"2020-08-11T00:00:00\",\"2020-08-12T00:00:00\",\"2020-08-13T00:00:00\",\"2020-08-14T00:00:00\",\"2020-08-15T00:00:00\",\"2020-08-16T00:00:00\",\"2020-08-17T00:00:00\",\"2020-08-18T00:00:00\",\"2020-08-19T00:00:00\",\"2020-08-20T00:00:00\",\"2020-08-21T00:00:00\",\"2020-08-22T00:00:00\",\"2020-08-23T00:00:00\",\"2020-08-24T00:00:00\",\"2020-08-25T00:00:00\",\"2020-08-26T00:00:00\",\"2020-08-27T00:00:00\",\"2020-08-28T00:00:00\",\"2020-08-29T00:00:00\",\"2020-08-30T00:00:00\",\"2020-08-31T00:00:00\",\"2020-09-01T00:00:00\",\"2020-09-02T00:00:00\",\"2020-09-03T00:00:00\",\"2020-09-04T00:00:00\",\"2020-09-05T00:00:00\",\"2020-09-06T00:00:00\",\"2020-09-07T00:00:00\",\"2020-09-08T00:00:00\",\"2020-09-09T00:00:00\",\"2020-09-10T00:00:00\",\"2020-09-11T00:00:00\",\"2020-09-12T00:00:00\",\"2020-09-13T00:00:00\",\"2020-09-14T00:00:00\"],\"y\":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,2199.40771484375,2199.40771484375,2225.533203125,2284.490478515625,2330.265869140625,2161.417236328125,2161.417236328125,2180.73193359375,2109.887939453125,2109.887939453125,2373.1083984375,2373.1083984375,2380.608642578125,2381.291015625,2381.291015625,2414.10400390625,2414.10400390625,2495.145751953125,2609.1767578125,2547.6044921875,2407.457763671875,2407.457763671875,2578.998779296875,2543.871337890625,2543.871337890625,2641.408935546875,2682.302978515625,2548.31201171875,2548.31201171875,2664.535888671875],\"type\":\"scatter\"},{\"fill\":\"tonexty\",\"line\":{\"color\":\"deeppink\"},\"mode\":\"lines\",\"name\":\"Max\",\"x\":[\"2020-02-20T00:00:00\",\"2020-02-21T00:00:00\",\"2020-02-22T00:00:00\",\"2020-02-23T00:00:00\",\"2020-02-24T00:00:00\",\"2020-02-25T00:00:00\",\"2020-02-26T00:00:00\",\"2020-02-27T00:00:00\",\"2020-02-28T00:00:00\",\"2020-02-29T00:00:00\",\"2020-03-01T00:00:00\",\"2020-03-02T00:00:00\",\"2020-03-03T00:00:00\",\"2020-03-04T00:00:00\",\"2020-03-05T00:00:00\",\"2020-03-06T00:00:00\",\"2020-03-07T00:00:00\",\"2020-03-08T00:00:00\",\"2020-03-09T00:00:00\",\"2020-03-10T00:00:00\",\"2020-03-11T00:00:00\",\"2020-03-12T00:00:00\",\"2020-03-13T00:00:00\",\"2020-03-14T00:00:00\",\"2020-03-15T00:00:00\",\"2020-03-16T00:00:00\",\"2020-03-17T00:00:00\",\"2020-03-18T00:00:00\",\"2020-03-19T00:00:00\",\"2020-03-20T00:00:00\",\"2020-03-21T00:00:00\",\"2020-03-22T00:00:00\",\"2020-03-23T00:00:00\",\"2020-03-24T00:00:00\",\"2020-03-25T00:00:00\",\"2020-03-26T00:00:00\",\"2020-03-27T00:00:00\",\"2020-03-28T00:00:00\",\"2020-03-29T00:00:00\",\"2020-03-30T00:00:00\",\"2020-03-31T00:00:00\",\"2020-04-01T00:00:00\",\"2020-04-02T00:00:00\",\"2020-04-03T00:00:00\",\"2020-04-04T00:00:00\",\"2020-04-05T00:00:00\",\"2020-04-06T00:00:00\",\"2020-04-07T00:00:00\",\"2020-04-08T00:00:00\",\"2020-04-09T00:00:00\",\"2020-04-10T00:00:00\",\"2020-04-11T00:00:00\",\"2020-04-12T00:00:00\",\"2020-04-13T00:00:00\",\"2020-04-14T00:00:00\",\"2020-04-15T00:00:00\",\"2020-04-16T00:00:00\",\"2020-04-17T00:00:00\",\"2020-04-18T00:00:00\",\"2020-04-19T00:00:00\",\"2020-04-20T00:00:00\",\"2020-04-21T00:00:00\",\"2020-04-22T00:00:00\",\"2020-04-23T00:00:00\",\"2020-04-24T00:00:00\",\"2020-04-25T00:00:00\",\"2020-04-26T00:00:00\",\"2020-04-27T00:00:00\",\"2020-04-28T00:00:00\",\"2020-04-29T00:00:00\",\"2020-04-30T00:00:00\",\"2020-05-01T00:00:00\",\"2020-05-02T00:00:00\",\"2020-05-03T00:00:00\",\"2020-05-04T00:00:00\",\"2020-05-05T00:00:00\",\"2020-05-06T00:00:00\",\"2020-05-07T00:00:00\",\"2020-05-08T00:00:00\",\"2020-05-09T00:00:00\",\"2020-05-10T00:00:00\",\"2020-05-11T00:00:00\",\"2020-05-12T00:00:00\",\"2020-05-13T00:00:00\",\"2020-05-14T00:00:00\",\"2020-05-15T00:00:00\",\"2020-05-16T00:00:00\",\"2020-05-17T00:00:00\",\"2020-05-18T00:00:00\",\"2020-05-19T00:00:00\",\"2020-05-20T00:00:00\",\"2020-05-21T00:00:00\",\"2020-05-22T00:00:00\",\"2020-05-23T00:00:00\",\"2020-05-24T00:00:00\",\"2020-05-25T00:00:00\",\"2020-05-26T00:00:00\",\"2020-05-27T00:00:00\",\"2020-05-28T00:00:00\",\"2020-05-29T00:00:00\",\"2020-05-30T00:00:00\",\"2020-05-31T00:00:00\",\"2020-06-01T00:00:00\",\"2020-06-02T00:00:00\",\"2020-06-03T00:00:00\",\"2020-06-04T00:00:00\",\"2020-06-05T00:00:00\",\"2020-06-06T00:00:00\",\"2020-06-07T00:00:00\",\"2020-06-08T00:00:00\",\"2020-06-09T00:00:00\",\"2020-06-10T00:00:00\",\"2020-06-11T00:00:00\",\"2020-06-12T00:00:00\",\"2020-06-13T00:00:00\",\"2020-06-14T00:00:00\",\"2020-06-15T00:00:00\",\"2020-06-16T00:00:00\",\"2020-06-17T00:00:00\",\"2020-06-18T00:00:00\",\"2020-06-19T00:00:00\",\"2020-06-20T00:00:00\",\"2020-06-21T00:00:00\",\"2020-06-22T00:00:00\",\"2020-06-23T00:00:00\",\"2020-06-24T00:00:00\",\"2020-06-25T00:00:00\",\"2020-06-26T00:00:00\",\"2020-06-27T00:00:00\",\"2020-06-28T00:00:00\",\"2020-06-29T00:00:00\",\"2020-06-30T00:00:00\",\"2020-07-01T00:00:00\",\"2020-07-02T00:00:00\",\"2020-07-03T00:00:00\",\"2020-07-04T00:00:00\",\"2020-07-05T00:00:00\",\"2020-07-06T00:00:00\",\"2020-07-07T00:00:00\",\"2020-07-08T00:00:00\",\"2020-07-09T00:00:00\",\"2020-07-10T00:00:00\",\"2020-07-11T00:00:00\",\"2020-07-12T00:00:00\",\"2020-07-13T00:00:00\",\"2020-07-14T00:00:00\",\"2020-07-15T00:00:00\",\"2020-07-16T00:00:00\",\"2020-07-17T00:00:00\",\"2020-07-18T00:00:00\",\"2020-07-19T00:00:00\",\"2020-07-20T00:00:00\",\"2020-07-21T00:00:00\",\"2020-07-22T00:00:00\",\"2020-07-23T00:00:00\",\"2020-07-24T00:00:00\",\"2020-07-25T00:00:00\",\"2020-07-26T00:00:00\",\"2020-07-27T00:00:00\",\"2020-07-28T00:00:00\",\"2020-07-29T00:00:00\",\"2020-07-30T00:00:00\",\"2020-07-31T00:00:00\",\"2020-08-01T00:00:00\",\"2020-08-02T00:00:00\",\"2020-08-03T00:00:00\",\"2020-08-04T00:00:00\",\"2020-08-05T00:00:00\",\"2020-08-06T00:00:00\",\"2020-08-07T00:00:00\",\"2020-08-08T00:00:00\",\"2020-08-09T00:00:00\",\"2020-08-10T00:00:00\",\"2020-08-11T00:00:00\",\"2020-08-12T00:00:00\",\"2020-08-13T00:00:00\",\"2020-08-14T00:00:00\",\"2020-08-15T00:00:00\",\"2020-08-16T00:00:00\",\"2020-08-17T00:00:00\",\"2020-08-18T00:00:00\",\"2020-08-19T00:00:00\",\"2020-08-20T00:00:00\",\"2020-08-21T00:00:00\",\"2020-08-22T00:00:00\",\"2020-08-23T00:00:00\",\"2020-08-24T00:00:00\",\"2020-08-25T00:00:00\",\"2020-08-26T00:00:00\",\"2020-08-27T00:00:00\",\"2020-08-28T00:00:00\",\"2020-08-29T00:00:00\",\"2020-08-30T00:00:00\",\"2020-08-31T00:00:00\",\"2020-09-01T00:00:00\",\"2020-09-02T00:00:00\",\"2020-09-03T00:00:00\",\"2020-09-04T00:00:00\",\"2020-09-05T00:00:00\",\"2020-09-06T00:00:00\",\"2020-09-07T00:00:00\",\"2020-09-08T00:00:00\",\"2020-09-09T00:00:00\",\"2020-09-10T00:00:00\",\"2020-09-11T00:00:00\",\"2020-09-12T00:00:00\",\"2020-09-13T00:00:00\",\"2020-09-14T00:00:00\"],\"y\":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,2501.0,2225.533203125,2284.490478515625,2429.271728515625,2429.271728515625,2330.265869140625,2180.73193359375,2448.458251953125,2448.458251953125,2377.91162109375,2377.91162109375,2380.608642578125,2655.49169921875,2655.49169921875,2547.405029296875,2547.405029296875,2495.145751953125,2700.324462890625,2700.324462890625,2609.1767578125,2547.6044921875,2578.998779296875,2748.90234375,2748.90234375,2641.408935546875,2682.302978515625,2700.677978515625,2700.677978515625,2664.535888671875,2671.16650390625],\"type\":\"scatter\"}],                        {\"template\":{\"data\":{\"histogram2dcontour\":[{\"type\":\"histogram2dcontour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"choropleth\":[{\"type\":\"choropleth\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"histogram2d\":[{\"type\":\"histogram2d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"heatmap\":[{\"type\":\"heatmap\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"heatmapgl\":[{\"type\":\"heatmapgl\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"contourcarpet\":[{\"type\":\"contourcarpet\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"contour\":[{\"type\":\"contour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"surface\":[{\"type\":\"surface\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"mesh3d\":[{\"type\":\"mesh3d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"scatter\":[{\"fillpattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2},\"type\":\"scatter\"}],\"parcoords\":[{\"type\":\"parcoords\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolargl\":[{\"type\":\"scatterpolargl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"bar\":[{\"error_x\":{\"color\":\"#2a3f5f\"},\"error_y\":{\"color\":\"#2a3f5f\"},\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"bar\"}],\"scattergeo\":[{\"type\":\"scattergeo\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolar\":[{\"type\":\"scatterpolar\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"histogram\":[{\"marker\":{\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"histogram\"}],\"scattergl\":[{\"type\":\"scattergl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatter3d\":[{\"type\":\"scatter3d\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermapbox\":[{\"type\":\"scattermapbox\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterternary\":[{\"type\":\"scatterternary\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattercarpet\":[{\"type\":\"scattercarpet\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"carpet\":[{\"aaxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"baxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"type\":\"carpet\"}],\"table\":[{\"cells\":{\"fill\":{\"color\":\"#EBF0F8\"},\"line\":{\"color\":\"white\"}},\"header\":{\"fill\":{\"color\":\"#C8D4E3\"},\"line\":{\"color\":\"white\"}},\"type\":\"table\"}],\"barpolar\":[{\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"barpolar\"}],\"pie\":[{\"automargin\":true,\"type\":\"pie\"}]},\"layout\":{\"autotypenumbers\":\"strict\",\"colorway\":[\"#636efa\",\"#EF553B\",\"#00cc96\",\"#ab63fa\",\"#FFA15A\",\"#19d3f3\",\"#FF6692\",\"#B6E880\",\"#FF97FF\",\"#FECB52\"],\"font\":{\"color\":\"#2a3f5f\"},\"hovermode\":\"closest\",\"hoverlabel\":{\"align\":\"left\"},\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"#E5ECF6\",\"polar\":{\"bgcolor\":\"#E5ECF6\",\"angularaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"radialaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"ternary\":{\"bgcolor\":\"#E5ECF6\",\"aaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"baxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"caxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"coloraxis\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"colorscale\":{\"sequential\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"sequentialminus\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"diverging\":[[0,\"#8e0152\"],[0.1,\"#c51b7d\"],[0.2,\"#de77ae\"],[0.3,\"#f1b6da\"],[0.4,\"#fde0ef\"],[0.5,\"#f7f7f7\"],[0.6,\"#e6f5d0\"],[0.7,\"#b8e186\"],[0.8,\"#7fbc41\"],[0.9,\"#4d9221\"],[1,\"#276419\"]]},\"xaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"yaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"scene\":{\"xaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"yaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"zaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2}},\"shapedefaults\":{\"line\":{\"color\":\"#2a3f5f\"}},\"annotationdefaults\":{\"arrowcolor\":\"#2a3f5f\",\"arrowhead\":0,\"arrowwidth\":1},\"geo\":{\"bgcolor\":\"white\",\"landcolor\":\"#E5ECF6\",\"subunitcolor\":\"white\",\"showland\":true,\"showlakes\":true,\"lakecolor\":\"white\"},\"title\":{\"x\":0.05},\"mapbox\":{\"style\":\"light\"}}},\"xaxis\":{\"anchor\":\"y\",\"domain\":[0.0,1.0],\"title\":{\"text\":\"Date\"}},\"yaxis\":{\"anchor\":\"x\",\"domain\":[0.0,1.0],\"title\":{\"text\":\"Confirmed Cases\"}},\"legend\":{\"title\":{\"text\":\"variable\"},\"tracegroupgap\":0},\"title\":{\"text\":\"Casos Confirmados\"}},                        {\"responsive\": true}                    )                };                            </script>        </div>\n```\n\n\nPronóstico de casos confirmados de COVID-19 en Irán en los próximos 30 días (implementación en python)\n:::\n:::\n\n:::\n\n::: {.content-visible when-format=\"pdf\"}\n![Pronostico de casos confirmados de COVID-19 en Irán (implementación en Python)](Imagenes/Confirmados.png){#fig-mlp1 fig-align=\"center\"}\n:::\n\n::: {.content-visible when-format=\"pdf\"}\n::: {style=\"text-align: justify\"}\nLos resultados del pronóstico en @fig-mlp1 indican que el 14 de Septiembre de 2020 se proyectan aproximadamente 2476 nuevos casos confirmados de COVID-19.\n:::\n:::\n\n::: {.content-visible when-format=\"html\"}\n::: {style=\"text-align: justify\"}\nLos resultados del pronóstico en @fig-mlp indican que el 14 de Septiembre de 2020 se proyectan aproximadamente 2476 nuevos casos confirmados de COVID-19.\n:::\n:::\n",
    "supporting": [
      "confirmados_files\\figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/htmlwidgets-1.6.2/htmlwidgets.js\"></script>\n<script src=\"site_libs/plotly-binding-4.10.2/plotly.js\"></script>\n<script src=\"site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"site_libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\n<link href=\"site_libs/crosstalk-1.2.0/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/crosstalk-1.2.0/js/crosstalk.min.js\"></script>\n<link href=\"site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\n<link href=\"site_libs/datatables-css-0.0.0/datatables-crosstalk.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/datatables-binding-0.30/datatables.js\"></script>\n<link href=\"site_libs/dt-core-bootstrap4-1.13.4/css/dataTables.bootstrap4.min.css\" rel=\"stylesheet\" />\n<link href=\"site_libs/dt-core-bootstrap4-1.13.4/css/dataTables.bootstrap4.extra.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/dt-core-bootstrap4-1.13.4/js/jquery.dataTables.min.js\"></script>\n<script src=\"site_libs/dt-core-bootstrap4-1.13.4/js/dataTables.bootstrap4.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}